### ISSUE TITLE
请问在新框架下，该如何订阅事件或者注册触发

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#1]
假如我想订阅游戏初始化事件

目前我做过的尝试有
```lua
local tigger1 = New 'Trigger' (New 'Event' (y3.const.GlobalEventType.GAME_INIT), function(data)
    dump(data)
end)
```
和
```lua
local event1 = New 'Event' (y3.const.GlobalEventType.GAME_INIT):add_trigger(function(data)
    dump(data)
end)
```

另外，这两个模块
[trigger.lua](https://github.com/y3-editor/y3-lualib/blob/main/util/trigger.lua)
[event.lua](https://github.com/y3-editor/y3-lualib/blob/main/util/event.lua)
都没有 return，只能通过 y3.class.get 获取或直接使用 New 'Trigger' ，以这种方式进行实例化如何实现 F12 跳转查看呢

**Comment by sumneko** [comment]
事件相关的功能我还没有提交，预计下周一可用

**Comment by xiazhixi** [comment]
> 

感谢解答

**Comment by sumneko** [comment]
全局事件已可用

**Comment by sumneko** [comment]
事件系统需要大整，规划见 https://github.com/y3-editor/y3-lualib/blob/main/%E4%BA%8B%E4%BB%B6%E7%B3%BB%E7%BB%9FTODO.md

**Comment by lanchengkai** [comment]
通常调试器附加成功时已经错过了游戏初始化时机，如果你想要追踪初始化相关的代码，可以在相关代码前面加一行 `LDBG:event 'wait'`。当游戏执行到此行代码时，游戏会“卡主”，直到调试器附加完成才会继续往下执行。

LDBG:event 'wait'
New 'Trigger' (New 'Event' '游戏-初始化', function()
    print('hellow world!')
end)

init.lua:1: attempt to index a nil value (global 'LDBG'

初始化事件好像还是有问题

**Comment by lanchengkai** [comment]
> 事件系统需要大整，规划见 https://github.com/y3-editor/y3-lualib/blob/main/%E4%BA%8B%E4%BB%B6%E7%B3%BB%E7%BB%9FTODO.md

通常调试器附加成功时已经错过了游戏初始化时机，如果你想要追踪初始化相关的代码，可以在相关代码前面加一行 LDBG:event 'wait'。当游戏执行到此行代码时，游戏会“卡主”，直到调试器附加完成才会继续往下执行。

```
LDBG:event 'wait'
New 'Trigger' (New 'Event' ('游戏-初始化'), function()
    print('hellow world!')
end)
```

init.lua:1: attempt to index a nil value (global 'LDBG'

初始化事件好像还是有问题
