### ISSUE TITLE
请问技能事件要怎么监听

### ISSUE THREAD

**Issue by baiyuek** [y3-editor/y3-lualib#10]
y3.game:event(y3.const.AbilityEventType.ABILITY_OBTAIN,function ()
        print("获得技能")
    end)

我像上面这样好像监听不到事件

**Comment by sumneko** [comment]
应为 `y3.const.AbilityEventType.ABILITY_OBTAIN`

**Comment by sumneko** [comment]
我测试是可以触发获得技能事件的

**Comment by baiyuek** [comment]
> 我测试是可以触发获得技能事件的，你确认一下是否是先注册了此事件再添加的技能？

额，我注册后立即添加技能不行，后面过一会儿再加技能可以了。

**Comment by sumneko** [comment]
> > 我测试是可以触发获得技能事件的，你确认一下是否是先注册了此事件再添加的技能？
> 
> 额，我注册后立即添加技能不行，后面过一会儿再加技能可以了。

目前的设计是脚本代码初始化的时候只能做定义相关的工作，创建单位、添加技能等动作需要在游戏初始化事件中才能做。
