### ISSUE TITLE
物品-进入背包 事件获取物品格子报错

### ISSUE THREAD

**Issue by sumneko** [y3-editor/y3-lualib#102]
当物品为堆叠类型, 背包内有该类型对应的物品且堆叠未达上限, 那么 item_slot 获取报错.
当背包栏不存在该物品或者该物品单格数量恰好为堆叠上限时正常获取.
```lua
y3.game:event("物品-进入背包", function(_, data)
    local item = data.item
	-- bug
    local item_slot = item:get_slot()
end)
```

_Originally posted by @xuhuanzy in https://github.com/y3-editor/y3-lualib/issues/101#issuecomment-1686741446_

**Comment by sumneko** [comment]
目前就是这么设计的，进入的物品被堆叠后会被移除，所以 `data.item` 取出来是 `nil` 。你可以根据 `data.item_no` 来获知物品的key。

**Comment by xuhuanzy** [comment]
> 目前就是这么设计的，进入的物品被堆叠后会被移除，所以 `data.item` 取出来是 `nil` 。你可以根据 `data.item_no` 来获知物品的key。

不是，能正常取出来，但handle那里显示堆叠数量为0，正常至少为1，用pcall处理了

**Comment by sumneko** [comment]
我深入测试了一下，真正的问题是获取物品的格子序号或格子类型时，如果物品并不在物品栏或背包栏里会直接报错

**Comment by xuhuanzy** [comment]
> 我深入测试了一下，真正的问题是获取物品的格子序号或格子类型时，如果物品并不在物品栏或背包栏里会直接报错

引擎的问题吧，毕竟触发了进入背包事件。
