### ISSUE TITLE
UI的get_name返回永远是`Button_00`

### ISSUE THREAD

**Issue by CabinIkaros** [y3-editor/y3-lualib#103]
![image](https://github.com/y3-editor/y3-lualib/assets/81321122/c81bb584-b1bc-4c99-86ba-70da015d59b2)

这里结果,期望是`runtime_ui_comp_0`

**Comment by sumneko** [comment]
可以用 `UI.handle` 获取，不过你为什么要获取它？

**Comment by CabinIkaros** [comment]
> 可以用 `UI.handle` 获取，不过你为什么要获取它？

在做一些UI的数据关联测试, lua这边UI实例获取每次都是new了一个新的UI实例返回(也就无法简单的ui.xxx=xxx),我就想着用ui的名字来做一些数据关联测试, 验证一些想法

我等会看看`ui.handle`,这个倒是被我忽略了

**Comment by CabinIkaros** [comment]
编辑器里ui不是有那个自定义数据功能么,但是应该是还没完成吧,我就是做类似这个的事情,因为ui会有他自己所属的自定义数据,比如在做英雄选择界面, 随机生成4个英雄选择ui, 这4个按钮所代表的英雄分别是谁

**Comment by sumneko** [comment]
UI这边我还没深入去看，之后会设计一套框架出来

**Comment by CabinIkaros** [comment]
> 

好的,幸苦了,排期计划有吗,我记录下

**Comment by CabinIkaros** [comment]
> 英雄

好的
