### ISSUE TITLE
希望尽快支持 lua 调试输出, 编辑器的日志很难用

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#104]
rt

**Comment by xuhuanzy** [comment]
@sumneko 希望日志加入自定义槽，方便在日志输出时执行自定义操作。例如输出到ui上。

**Comment by xuhuanzy** [comment]
@sumneko 希望日志增加自定义委托，类似object.lua里的委托调用链，需要判断不同等级。

**Comment by sumneko** [comment]
没听懂你的需求，给个例子？

**Comment by xuhuanzy** [comment]
> 没听懂你的需求，给个例子？

就是在log输出时先调用自定义的回调函数。

**Comment by xuhuanzy** [comment]
> 没听懂你的需求，给个例子？

大概是这样
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/f8c70550-15f7-4680-905a-b34948983833)

**Comment by xuhuanzy** [comment]
有没有可能日志输出到终端? 
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/cfb55db5-fe84-47b0-a237-4b58d2c3fedc)

另外输出到本地文件是无效的吧? 搜索找不到日志文件

**Comment by sumneko** [comment]
> 另外输出到本地文件是无效的吧? 搜索找不到日志文件

目前无效，要等等
