### ISSUE TITLE
资源问题

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#108]
项目移动到另外一台电脑时，图标资源(lua内指定)没有被编辑器识别下载，导致set_image设置了一张白图。
该资源是官方资源商店内的，如何使之自动下载？

**Comment by sumneko** [comment]
在表格编辑器中随便建一张表格，然后把你用的资源都填进去即可。
表格编辑器支持导入CSV，你可以写个脚本生成CSV文件然后导入

**Comment by xuhuanzy** [comment]
> 在表格编辑器中随便建一张表格，然后把你用的资源都填进去即可。 表格编辑器支持导入CSV，你可以写个脚本生成CSV文件然后导入

`resource.lua`声明无效吗?

**Comment by sumneko** [comment]
> `resource.lua`声明无效吗?

没听说过有这个功能

**Comment by xuhuanzy** [comment]
> > `resource.lua`声明无效吗?
> 
> 没听说过有这个功能

之前创建lua库时有resource.lua, 与main.lua同级. 刚试了下声明, 部分资源成功, 部分资源失败(白图)

**Comment by sumneko** [comment]
可能是已经废弃的功能，还是用表格编辑器做吧
