### ISSUE TITLE
实时获取摄像机焦点api不起作用

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#111]
camera.get_camera_center_raycast

获取的永远是 {Point|0.000,0.000,0.000}

**Comment by sumneko** [comment]
我测试是正常的，这个功能需要同步，如果你启用同步后立即去获取是取不到的。

**Comment by sumneko** [comment]
你要做什么功能呢，开个需求吧

**Comment by xiaoqiangCai** [comment]
> 你要做什么功能呢，开个需求吧

最需要：
1. 禁止玩家滚轮对镜头的操作
