### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#113]
拉取新版后运行游戏报错：LuaError: virtual_script/y3/tools/reload.lua:146: 不能混用 `require` 与 `include` 加载 "y3.develop.command"

**Comment by sumneko** [comment]
你是在平台里运行的地图吗？

**Comment by padoruuu** [comment]
本地-独立进程
那个初始化配置.bat我运行会出错，就手动把配置丢到项目根目录了

下面遇到的新问题，输入.SS后：
virtual_script/y3/develop/command.lua:45: attempt to index a nil value (field 'doctor')

**Comment by padoruuu** [comment]
[2023-08-29-14-53-31] : [Error]: error during Python call
stack traceback:
	virtual_script/y3/develop/command.lua:56: in local 'f'
	virtual_script/y3/develop/command.lua:99: in function <virtual_script/y3/develop/command.lua:80>
	[C]: in function 'xpcall'
	virtual_script/y3/util/trigger.lua:91: in method 'execute'
	virtual_script/y3/util/event.lua:91: in method 'dispatch'
	virtual_script/y3/util/event_manager.lua:100: in method 'dispatch'
	virtual_script/y3/game/game_event.lua:48: in function 'y3.game.game_event.event_notify'
	virtual_script/y3/game/py_event_subscribe.lua:220: in function <virtual_script/y3/game/py_event_subscribe.lua:218>
