### ISSUE TITLE
禁止玩家滚轮对镜头的操作

### ISSUE THREAD

**Issue by sumneko** [y3-editor/y3-lualib#116]
> 你要做什么功能呢，开个需求吧

最需要：
1. 禁止玩家滚轮对镜头的操作

_Originally posted by @xiaoqiangCai in https://github.com/y3-editor/y3-lualib/issues/111#issuecomment-1699048617_

**Comment by sumneko** [comment]
用 `Player:set_mouse_wheel(false) ` 即可

**Comment by xiaoqiangCai** [comment]
> 用 `Player:set_mouse_wheel(false) ` 即可

我试了一下，eca的可以用，lua的api不生效

**Comment by sumneko** [comment]
我测试了一下是有效的呀，你具体环境是啥

**Comment by xiaoqiangCai** [comment]
> 我测试了一下是有效的呀，你具体环境是啥

我的问题~，搞错测试用例了，是可以用的，感谢
