### ISSUE TITLE
GameAPI.get_screen_x_resolution()获取分辨率有误

### ISSUE THREAD

**Issue by tzw-1998** [y3-editor/y3-lualib#12]
GameAPI.get_screen_x_resolution()
GameAPI.get_screen_y_resolution()
获取的非游戏内分辨率，而是Win屏幕分辨率，导致游戏内UI偏移
![6K_V 1 @((U@$Z%8 O)NV7](https://github.com/y3-editor/y3-lualib/assets/29767139/ee6c4f7d-50a6-46f9-90db-4da3333b2e98)
![N}`6QJ0(SETEJ JAYEDWM](https://github.com/y3-editor/y3-lualib/assets/29767139/4bd706d5-42ad-4b14-9df7-3ba4615cd9ea)

**Comment by sumneko** [comment]
这个API的名字就是“获取屏幕x”，你想要的应该是 `GameAPI.get_window_real_x_size`

**Comment by 200774491** [comment]
我测试了一下 print("屏幕横向分辨率:",GameAPI.get_window_real_x_size())
会提示没有这个func
[2023-07-10-18-25-49] : [Error]: Lua代码出错:"'GameAPI' object has no attribute 'get_window_real_x_size'"
[Lua] error reading Python attribute/item

**Comment by 200774491** [comment]
> 这个API的名字就是“获取屏幕x”，你想要的应该是 `GameAPI.get_window_real_x_size`

我测试了一下 print("屏幕横向分辨率:",GameAPI.get_window_real_x_size())
会提示没有这个func
[2023-07-10-18-25-49] : [Error]: Lua代码出错:"'GameAPI' object has no attribute 'get_window_real_x_size'"
[Lua] error reading Python attribute/item

**Comment by sumneko** [comment]
已转至引擎的需求

**Comment by sumneko** [comment]
事实上目前的UI系统自带排版系统，可以直接让某个面板居中，不需要自己算。你先自己尝试一下？

**Comment by 200774491** [comment]
以后不会修复这个api的问题？
使用界面编辑器很不习惯点点点

**Comment by sumneko** [comment]
这个功能已经作为需求提上去了，重新开放需要等后面某次版本更新。

**Comment by sumneko** [comment]
下个版本放出
