### ISSUE TITLE
event "界面-创建"与"界面-移除" 疑似没有效果

### ISSUE THREAD

**Issue by MouJiaoZi** [y3-editor/y3-lualib#123]
在正常生效的lua文件内
y3.game:event("界面-创建", function() do something end)
以及移除事件，都没有任何反应，看触发器没找到相关事件，是否是官方移除了这些东西？

另一个问题：
在lua端如何判断一个可能被执行了ui:remove()的ui是否还存在呢？

**Comment by sumneko** [comment]
> y3.game:event("界面-创建", function() do something end)
> 以及移除事件，都没有任何反应，看触发器没找到相关事件，是否是官方移除了这些东西？

应该是移除了，我先把它们去掉吧
