### ISSUE TITLE
本地多开模式创建问题

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#126]
单位创建并非是同步的，例如在A与B玩家的lua里，初始化时取本地玩家，然后只为这个本地玩家创建一个单位，那么A与B玩家游戏里只会看到一个单位，单位ID一致且player不同。
这是机制还是bug？

**Comment by sumneko** [comment]
设计如此

**Comment by xuhuanzy** [comment]
> 设计如此

`editable_object`里的都必须要为每个客户端独立创建?

**Comment by xuhuanzy** [comment]
@sumneko 有没有同步案例? 
现在有两个客户端, 一个客户端里独自打开背包, 为自己的单位穿上了装备.
但另一个客户端并不知道这个单位穿了新装备, 怎么做才能通知到这个客户端?

**Comment by sumneko** [comment]
> @sumneko 有没有同步案例? 现在有两个客户端, 一个客户端里独自打开背包, 为自己的单位穿上了装备. 但另一个客户端并不知道这个单位穿了新装备, 怎么做才能通知到这个客户端?

UI是同步创建的话，相关事件也会是同步的

**Comment by xuhuanzy** [comment]
ui无法同步创建吧? 多开我报错了, 创建不了属于非本地玩家的ui, 于是我加上了非本地玩家不做创建

**Comment by sumneko** [comment]
创建UI的接口 `create_ui` 的第一个参数就是玩家呀

**Comment by xuhuanzy** [comment]
> 创建UI的接口 `create_ui` 的第一个参数就是玩家呀

![image](https://github.com/y3-editor/y3-lualib/assets/90585805/e2fc0899-bbb5-4220-bed8-55680842c236)
多开时我这句报了nil value

**Comment by sumneko** [comment]
> 多开时我这句报了nil value

是有一部分玩家报 `nil` ，一部分正常工作？可以提供个演示图吗？

**Comment by xuhuanzy** [comment]
跟ui创建关系也不大, 主要问题是, 我应该怎么做才能在单独的客户端里操作独立的东西( 比如说 ui 界面 ), 在这个独立的操作里为自己的单位执行了某些操作( 比如说穿装备 ), 怎么才能通知到所有客户端?

**Comment by sumneko** [comment]
默认就是会通知所有客户端的。你给某个玩家创建UI时其实所有玩家都创建了这个UI，但只有指定的这个玩家会显示出来。他对该UI进行操作时所有的玩家都会触发此UI的事件。

**Comment by xuhuanzy** [comment]
> 你给某个玩家创建UI时其实所有玩家都创建了这个UI

所以ui应该由本地玩家创建?

**Comment by sumneko** [comment]
> 所以ui应该由本地玩家创建?

创建UI的接口 `create_ui` 的第一个参数就是玩家呀

**Comment by xuhuanzy** [comment]
能给个操作例子吗?

**Comment by sumneko** [comment]
```lua
y3.game:event('游戏-初始化', function ()
    for i = 1, 10 do
        local ui = y3.ui.get_ui(y3.player(i), 'panel_1.image_1')
        ui:add_event('鼠标-移入', '测试事件')
    end
end)

-- 接收UI事件
y3.game:event('界面-消息', '测试事件', function (trg, data)
    print('触发事件的玩家为：', data.player)
end)
```

**Comment by xuhuanzy** [comment]
在为非本地玩家操作时出现了这个问题, 原来是bug吗? 
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/dcc873e4-9759-498f-a46f-1a30238876d6)

![image](https://github.com/y3-editor/y3-lualib/assets/90585805/b73774a2-7582-47fd-af14-4000bf9a2b6c)

**Comment by sumneko** [comment]
> 在为非本地玩家操作时出现了这个问题, 原来是bug吗?

单机有问题吗？多人有问题的话，是所有人都有问题还是一部分人有问题？

**Comment by xuhuanzy** [comment]
单机没有, `本地多开游戏`有, 2个客户端, 2个客户端在为非本地玩家执行这个时都报错了, 为本地玩家创建没有问题

**Comment by sumneko** [comment]
移步到 #137 中追踪此问题
