### ISSUE TITLE
未来会支持英萌框架吗

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#13]
接触LUA作图就是学的英萌框架，请问您未来会支持英萌那种写法吗

**Comment by sumneko** [comment]
具体指的是哪种？

**Comment by padoruuu** [comment]
> 具体指的是哪一种？

就像英萌那样写技能 写buff等 并且有ini物编

**Comment by sumneko** [comment]
> > 具体指的是哪一种？
> 
> 就像英萌那样写技能 写buff等 并且有ini物编

前者会尽快实现，后者需要一段时间
