### ISSUE TITLE
请求: 支持自定义 `trigger:is_match_args`

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#131]
rt

**Comment by sumneko** [comment]
没懂

**Comment by xuhuanzy** [comment]
> 没懂

可以允许这个自定义? 
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/3a7f2156-f5c8-4a77-a56a-59bc0642f472)

**Comment by sumneko** [comment]
不能。你想要做什么？

**Comment by xuhuanzy** [comment]
> 不能。你想要做什么？

没啥, 觉得事件多起来在事件内过滤有点过于重复了, 也不是大问题, 我往`custom_event.lua`塞几个api完活了.
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/ea164910-a4ca-4aaa-8ac7-70c3cbc83c38)

![image](https://github.com/y3-editor/y3-lualib/assets/90585805/453bdabf-2c7f-4f7a-883a-169850f2dc26)

`notify`里有`dispatch`的会插入结算吗?

**Comment by sumneko** [comment]
> 没啥, 觉得事件多起来在事件内过滤有点过于重复了, 也不是大问题, 我往`custom_event.lua`塞几个api完活了.

可以的话尽量自己细分事件名吧。支持参数只是为了兼容以前的设计。

**Comment by sumneko** [comment]
> `notify`里有`dispatch`的会插入结算吗?

`dispatch` 无视队列会插入结算
