### ISSUE TITLE
gameevent.lua

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#14]
gameevent.lua中
分发事件似乎不全,没有的是否暂时无法使用
例如:动态创建的UI的事件？

**Comment by 200774491** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/e0047058-5052-47bd-bcc4-6fc229e85445)

**Comment by sumneko** [comment]
事件系统的进度请参阅：https://github.com/y3-editor/y3-lualib/blob/main/%E4%BA%8B%E4%BB%B6%E7%B3%BB%E7%BB%9FTODO.md

**Comment by myrainbowcolor** [comment]
_G.dump = function(data)
    print(y3.util.dump(data))
end
-------
dump建议这样包一下

**Comment by myrainbowcolor** [comment]
`_G.dump = function(data)
    print(y3.util.dump(data))
end`
dump建议这样包一下
