### ISSUE TITLE
疑似全局触发器泄露

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#146]
---@field event fun(self: self, event: "区域-进入", area: Area, callback: fun(trg: Trigger, data: EventParam.区域-进入)): Trigger
---@field event fun(self: self, event: "区域-离开", area: Area, callback: fun(trg: Trigger, data: EventParam.区域-离开)): Trigger

这两个事件，都会创建一个全局触发器，但如果area是动态生成的，临时性的，这个全局触发器的销毁逻辑是什么

问题：
1. 销毁动态的area，会自动清理创建的全局触发器吗
2. 好像也没有动态销毁全局触发器的API

**Comment by sumneko** [comment]
1. 使用 `Area:event('区域-进入', function () end)` 会自动清理，使用 `ac.game:event('区域-进入', Area, function () end)` 则不会。
2. 注册触发器会返回 `Trigger` 对象，使用 `Trigger:remove()` 删除触发器。

**Comment by sumneko** [comment]
确实，我晚点改一下
