### ISSUE TITLE
区域触发器通过链创建似乎无效 2.0 编辑器

### ISSUE THREAD

**Issue by ldoubil** [y3-editor/y3-lualib#148]
比如
`y3.area.create_circle_area(self.spawnPoint,self.Boos_realm):event("区域-进入",fun) `
就不会触发区域进入

但是直接创建就可以触发
` y3.game:event("区域-进入",y3.area.create_circle_area(self.spawnPoint,self.Boos_realm),function (_,data)
           
        end)`

**Comment by ldoubil** [comment]
刚创建的区域无法立马创建事件需要等待一阵子才行比如.

local a = y3.area.create_circle_area(self.spawnPoint,self.Boos_realm)
        y3.timer.wait(2,function (timer)
             y3.game:event("区域-进入",a,function (_,data)
            D( data.unit:get_owner_player():get_name().."进入了区域")
        end)
        end)

**Comment by ldoubil** [comment]
测试好像也不是延迟创建的问题,而是动态创建的区域如果赋予事件,那么在触发的时候就会报错不支持的区域类型

**Comment by ldoubil** [comment]
又测试了一次,这个问题只会在,在编辑器内运行的时候触发,而且包括获取自定义键值,如果在编辑器内运行,就会警告,未取到,但是实际取到了

**Comment by sumneko** [comment]
你试试在游戏初始化事件里再创建区域

**Comment by ldoubil** [comment]
> 你试试在游戏初始化事件里再创建区域

确认问题了,只有在编辑器内运行的时候会报错和提示,独立运行就不提示和报错了.
