### ISSUE TITLE
技能模板修改属性不生效

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#150]
物编创建一个主动技能，目标指示器，索敌阵营是空的，索敌类型全部的技能模板，游戏中用这个模板添加到单位上，然后修改索敌目标阵营信息，不生效

问题：
1. 目前是通过 ability.handle:api_set_int_attr("filter_condition_camp",2^1) 来设置, filter_condition_camp 是查看的导出的数据里面归属索敌的属性，属性值时设置上了，但是实际技能索敌的目标阵营还是没有变化
2. 如果要变更索敌阵营怎么操作呢

**Comment by sumneko** [comment]
触发器能用吗，如果不能的话应该就是不能

**Comment by xiaoqiangCai** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/7403230/a5ebad07-4a5a-4976-91f8-ac3a40151dbe)
 
eca里面只有这几个预设的，并且无法传自定义的key，看着像是没有提供这个功能...这提个需求

另外问个题外话，2.0的y3现在lua是能debug的吗

**Comment by sumneko** [comment]
> eca里面只有这几个预设的，并且无法传自定义的key，看着像是没有提供这个功能...这提个需求

需求走论坛或者群提吧

> 另外问个题外话，2.0的y3现在lua是能debug的吗

更新最新的调试器与LuaLib就可以

**Comment by xiaoqiangCai** [comment]
> > eca里面只有这几个预设的，并且无法传自定义的key，看着像是没有提供这个功能...这提个需求
> 
> 需求走论坛或者群提吧
> 
> > 另外问个题外话，2.0的y3现在lua是能debug的吗
> 
> 更新最新的调试器与LuaLib就可以

好的
