### ISSUE TITLE
无法创建界面实例

### ISSUE THREAD

**Issue by snailzzj** [y3-editor/y3-lualib#155]
一、
local goods_bg = y3.ui.get_ui(player, 'panel_1.shop_bg.shop.goods_bg')
local goods_prefab = '4bf746d5-e098-428b-9d98-50875333b102'
local ui_prefab = y3.ui_prefab.create(player, goods_prefab, goods_bg)
ui_prefab:get_ui(player):set_pos(95, 355)

二、
GameAPI.create_ui_prefab_instance(y3.player(1).handle, "4bf746d5-e098-428b-9d98-50875333b102", "panel_1")

上述两种方式都无法创建出UI，编辑版本2.0.7

以下ECS有效：
![image](https://github.com/y3-editor/y3-lualib/assets/10493464/5b3c5639-3865-46ba-b021-2e84bf88443c)

**Comment by ldoubil** [comment]
测试2.0.7可以创建,检查你的代码
