### ISSUE TITLE
存档问题【严重】

### ISSUE THREAD

**Issue by JinkenLenakin** [y3-editor/y3-lualib#158]
可以通过player:get_save_data_table 读取玩家存档。但没有将表格类存档进行存档的函数。有一个 Role:set_save_data_table_value 函数，但使用后并不会进行存档（这个函数比较奇怪，在没有存档时运行游戏是可写入存档信息的，一旦运行游戏时已经有存档了，使用这个函数会导致存档清空，且函数不再生效）。

**Comment by sumneko** [comment]
经检查是用户的操作有问题，关闭。
