### ISSUE TITLE
坐标移动距离过大会导致画面闪过物品

### ISSUE THREAD

**Issue by sumneko** [y3-editor/y3-lualib#16]
坐标移动距离过大会导致画面闪过物品, 但移动失败, -5000改成-3000以内成功移动. 
在延时函数里再套一个延时分两段移动可以成功移动.
 ```
local item = y3.item.create_item(y3.point.create(-5000,-5000), 134239351, y3.player)
    y3.timer.wait(2.0, function()
        item:set_point(y3.point.create(-379.47, -73.35))
    end)

```

_Originally posted by @xuhuanzy in https://github.com/y3-editor/y3-lualib/issues/11#issuecomment-1625320941_

**Comment by sumneko** [comment]
@xuhuanzy 使用ECA执行这个动作会有问题吗？得先确认一下是否是引擎的问题。

**Comment by xuhuanzy** [comment]
> @xuhuanzy 使用ECA执行这个动作会有问题吗？得先确认一下是否是引擎的问题。

eca复现了, 估计是引擎问题

**Comment by sumneko** [comment]
我这边无法复现，请提供一下演示地图

**Comment by xuhuanzy** [comment]
> 我这边无法复现，请提供一下演示地图

[test.zip](https://github.com/y3-editor/y3-lualib/files/12012165/test.zip)
在物编新建了个物品模板, 触发器里写的移动.

**Comment by xuhuanzy** [comment]
编辑器更新已修复
