### ISSUE TITLE
bindGC死循环删除

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#163]
父类实例bindGC子类实例, 父类调用__del()会导致死循环.

```lua
---@class Item.Equip: Item
---@field public base Item
local M = Class('Item.Equip', "Item")

function M:__init(id)
    local item = y3.item.get_by_id(id)
    self.handle = item.handle
    self.id = item.id
    self.base = item

    self.base:bindGC(self)

    return self
end
```

![image](https://github.com/y3-editor/y3-lualib/assets/90585805/029c1991-8207-4ad7-b705-35019da5fdc9)

**Comment by xuhuanzy** [comment]
> 并没有死循环，是因为 `Item.Equip` 和 `self.base` 各自触发了一次 `__del`，但是 `self.handle` 不支持调用2次 `self.handle:api_remove()`，所以报错了。
> 
> 而且你的做法很怪，如果你是用 `Equip` 继承了 `Item` 的话，那么 `self` 就已经是 `Item` 了，不应该再把它记在 `base` 字段里。 你可以整理一下需求，我帮你想想怎么做。

已经换了做法了，新建了方法根据id取item，毕竟这两个的id是一致的。
想要实现的是item删除的同时把这个实例也删除，现在是在equip里挂了下物品移除事件解决的。

**Comment by sumneko** [comment]
> > 并没有死循环，是因为 `Item.Equip` 和 `self.base` 各自触发了一次 `__del`，但是 `self.handle` 不支持调用2次 `self.handle:api_remove()`，所以报错了。
> > 而且你的做法很怪，如果你是用 `Equip` 继承了 `Item` 的话，那么 `self` 就已经是 `Item` 了，不应该再把它记在 `base` 字段里。 你可以整理一下需求，我帮你想想怎么做。
> 
> 已经换了做法了，新建了方法根据id取item，毕竟这两个的id是一致的。 想要实现的是item删除的同时把这个实例也删除，现在是在equip里挂了下物品移除事件解决的。

因为你继承的时候会把父类的方法拷贝过来，但是实际上运行时同时存在了父类和子类的实例（标准的继承里是只会创建一个子类实例的），导致父类和子类的 `__del` 各执行了一次，但是刚好这个 `__del` 不支持多次运行。

比较简单的办法是，你在子类里面注册一个空的 `__del` 。但是总体来说这个做法是不好的，我猜你写继承只是为了复用父类的接口罢了，并不想继承父类的构造与析构，所以你得建个自己的析构。

**Comment by xuhuanzy** [comment]
父类的析构是默认继承的吧? 我测的时候是先执行父类析构再执行子类析构, 构造函数倒没注意

**Comment by sumneko** [comment]
因为继承不是给你这么用，他一般是用于比如 `Point3: Point2`，实际运行时只有 `Point3` 这一个实例，并不存在对应的 `Point2` 。

**Comment by xuhuanzy** [comment]
> 因为继承不是给你这么用，他一般是用于比如 `Point3: Point2`，实际运行时只有 `Point3` 这一个实例，并不存在对应的 `Point2` 。

但继承自item的情况下, 实际上是存在一个base的, 这里是拿base关联这个而不是自己关联自己

**Comment by sumneko** [comment]
对于继承来说并不存在 `base`，因为它就是 `self`。如果你没有偷懒复用接口的需求的话，你显然是不会写继承的。

**Comment by xuhuanzy** [comment]
这个base是想后面移除掉继承而保留的... 
继承item需要的就是这两步吧
```lua
    self.handle = item.handle
    self.id = item.id
```

**Comment by xuhuanzy** [comment]
> 对于继承来说并不存在 `base`，因为它就是 `self`。如果你没有偷懒复用接口的需求的话，你显然是不会写继承的。

其实这个base还是那么点用处的, 比如说挂状态挂标签. 毕竟事件拿到的是item缓存而不是子类缓存, 直接给item挂省了点事
