### ISSUE TITLE
> y3.game.event('区域-进入/离开', area, function)正常 area.event 无效

### ISSUE THREAD

**Issue by MouJiaoZi** [y3-editor/y3-lualib#169]
> y3.game.event('区域-进入/离开', area, function)正常 area.event 无效

我自己测试是有效的，而且 `area:event` 是在Lua中实现的，最终会转换成 `y3.game:event` ，要失效的话应该是2个都失效才对。

_Originally posted by @sumneko in https://github.com/y3-editor/y3-lualib/issues/159#issuecomment-1772157034_
            
在编辑器内运行下，使用y3.area.create_rectangle_area创建的矩形区域，在y3.game.event()的区域触发里提示报错 不支持的区域类型
```
 in function 'debug.traceback'
	[C]: in function 'y3.tools.class._errorHandler'
	y3\object\scene_object\area.lua:67: in function 'y3.object.scene_object.area.get_by_res_id'
```
多开模式无报错

**Comment by MouJiaoZi** [comment]
经测试，编辑器内运行，y3.game.event的正方形区域，报错提示不支持的区域类型，实际代码有效
area.event的正方形区域，报错不支持的区域类型，代码无效
多开模式下，二者均无报错，area.event代码无效

**Comment by sumneko** [comment]
这个你先用全局的写法吧，要等11月2号的版本能用新的API后才能解决
