### ISSUE TITLE
关于帧回调

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#174]
hi，

lua库和eca里面关于帧回调，有点混乱了，咨询以下问题：

1. 最新版的timer中的 frame timer 相关标记为丢弃, 建议使用 ltimer 中的, 而 ltimer 中的 frame 又是使用原来的 timer 的中 loop_frame 的中心分发, 所以这个帧回调是异步的还是同步的？该怎么理解ltimer中的frame
2. 之前的版本中game:event下有 `"时间-经过帧"` 和 `"时间-周期帧"` 两个事件我看已经移除了，这个是等同于ECA中的帧事件的吧，是同步事件，对吧
3. 如果 ltimer 中的 frame 是异步的，是不是说明lua库里没有直接的同步帧回调了？

**Comment by sumneko** [comment]
> 1. 最新版的timer中的 frame timer 相关标记为丢弃, 建议使用 ltimer 中的, 而 ltimer 中的 frame 又是使用原来的 timer 的中 loop_frame 的中心分发, 所以这个帧回调是异步的还是同步的？该怎么理解ltimer中的frame

描述有点问题，`ltimer` 指的是计时器支持异步注册、异步回调，而原来的 `timer` 不支持（异步注册或回调会直接引发游戏不同步错误）。理论上可以全部使用 `ltimer` 替代 `timer`

> 2\. 之前的版本中game:event下有 `"时间-经过帧"` 和 `"时间-周期帧"` 两个事件我看已经移除了，这个是等同于ECA中的帧事件的吧，是同步事件，对吧

是的

> 3\. 如果 ltimer 中的 frame 是异步的，是不是说明lua库里没有直接的同步帧回调了？

只要是同步注册的就是同步回调的，还是描述的问题，我等会儿改一下。

**Comment by xiaoqiangCai** [comment]
好的。

>描述有点问题，ltimer 指的是计时器支持异步注册、异步回调，而原来的 timer 不支持（异步注册或回调会直接引发游戏不同步错误）。理论上可以全部使用 ltimer 替代 timer

这里的异步回调怎么理解？都异步回调了咋替代timer，我理解目前的timer都是同步的，如果timer变异步了那不是还得提供一个数据同步的接口？

**Comment by sumneko** [comment]
> 这里的异步回调怎么理解？

既支持同步也支持异步
