### ISSUE TITLE
VScodeF5调试时提示找不到文件

### ISSUE THREAD

**Issue by jiangshancoder** [y3-editor/y3-lualib#175]
main.lua里面直接require “y3”
发生异常: script/y3/init.lua:9: module 'y3.tools.proxy' not found:
	no field package.preload['y3.tools.proxy']
	no file 'E:\gitee\y3-demo\MapName001/y3\tools\proxy.lua'
	no file 'E:\gitee\y3-demo\MapName001/y3\tools\proxy.lua'
	no file 'E:\gitee\y3-demo\MapName001/y3\tools\proxy.dll'
	no file 'E:\gitee\y3-demo\MapName001/y3\tools\proxy.dll'
	no file 'E:\gitee\y3-demo\MapName001/y3.dll'
	no file 'E:\gitee\y3-demo\MapName001/y3.dll'

是需要自己加y3的path吗？

**Comment by sumneko** [comment]
本地有这个文件吗？

**Comment by jiangshancoder** [comment]
有啊，lua逻辑应该都在script文件夹是吧。
我新创建地图，然后将本项目所有文件覆盖替换到地图的script/y3 文件夹里面。
入口lua文件是script/main.lua是吧
然后我在main.lua中  require "y3"，就会有这个报错。
![image](https://github.com/y3-editor/y3-lualib/assets/31840262/1481ab46-1dcb-486a-828c-0345e373b6e4)
![image](https://github.com/y3-editor/y3-lualib/assets/31840262/24b10e38-b497-40e9-9051-692186db622b)
![image](https://github.com/y3-editor/y3-lualib/assets/31840262/58df3de1-b8f5-4e11-ae6d-80c71602dfa5)

我描述清楚了吗~

**Comment by sumneko** [comment]
y3目录往外挪一层（去掉 script 目录）

**Comment by jiangshancoder** [comment]
对不起~我看readme理解错了~
