### ISSUE TITLE
UI:add_event 2.0报错

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#176]
` [Error]: error during Python call`

而且在2.0多开模式下, 不同玩家对同个ui进行`add_event` 爆黄`: [Warning]: code_create_event_fail_by_double_name:xxx`. 
`add_event`自定义数据每个玩家是独立的?

**Comment by sumneko** [comment]
报错截图看看？

**Comment by xuhuanzy** [comment]
> 报错截图看看？

哪个的?

**Comment by sumneko** [comment]
就是你标题的。截图包括你的代码和错误日志

**Comment by xuhuanzy** [comment]
```lua
---@private
---@param player Player
---@return string[]
function M.init_items(player)
    local baseboard = y3.ui.get_by_handle(player, M.config.this)
    local items     = baseboard:get_child("items")
    assert(items)
    local ret = container()

    for _, item_ui in ipairs(items:get_ui_comp_children()) do
        -- 阻止右键点击事件以实现自己的右键菜单
        local equip_icon_img = item_ui:get_child('equip_icon_img')
        -- 注册事件
        local event_ui = equip_icon_img
        assert(event_ui)
        event_ui:add_event("鼠标-移入", M.config.items.event_name.show_tip)
        event_ui:add_event("鼠标-移出", M.config.items.event_name.hide_tip)

        -- 按顺序添加
        table.insert(ret, event_ui.handle)
    end

    return ret
end
```

爆重复(仅限多人模式):
将`add_event`改回原来的
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/d13fa85b-ab01-40e3-808a-c83af5a2e940)

报错: 
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/c4fb0ca7-c1d0-4fb8-b08d-ff4a74ac88f4)



报错: 
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/3dc2065e-7f7e-48c9-a2d7-f911d75e9a4d)

**Comment by sumneko** [comment]
你把 `y3\object\scene_object\ui.lua` 第74行改成 `    return GameAPI.create_ui_comp_event_ex_ex(self.handle, y3.const.UIEventMap[event] or event, name)` 看看还会不会报错

**Comment by xuhuanzy** [comment]
> 你把 `y3\object\scene_object\ui.lua` 第74行改成 ` return GameAPI.create_ui_comp_event_ex_ex(self.handle, y3.const.UIEventMap[event] or event, name)` 看看还会不会报错

这个不就是我上面的截图的吗? 去了data参数后不会报错, 但仍然会出现爆重复的黄色警告.

**Comment by xuhuanzy** [comment]
应该是两个问题.
1. 不同玩家对同个ui执行add_event会爆重复警告
2. `add_event`在2.0添加`data`参数后报错, 去除正常

**Comment by sumneko** [comment]
> 这个不就是我上面的截图的吗? 去了data参数后不会报错, 但仍然会出现爆重复的黄色警告.

你上面那个截图内容和你说的内容不符，我没看懂。总之我先把报错改了，这个警告是啥我也不知道，得去问问

**Comment by sumneko** [comment]
仔细看了下警告原因应该是每个事件名只能用一次，你这里遍历了很多个空间都注册了这同一个名字的事件，所以给了警告。我觉得这个设计不太合理，我晚点搞个更高级的封装解决一下。

**Comment by xuhuanzy** [comment]
> 仔细看了下警告原因应该是每个事件名只能用一次，你这里遍历了很多个空间都注册了这同一个名字的事件，所以给了警告。我觉得这个设计不太合理，我晚点搞个更高级的封装解决一下。

可能是bug, 问问引擎的? 1.0我记得没这个问题.
这里是对不同ui注册同个事件名, 编辑器的界面编辑器是允许这样的. 问题出在不同玩家对同个ui注册了同名事件, 应该是底层不区分玩家? 
所以我才问自定义数据是不是每个玩家独立的.

**Comment by xuhuanzy** [comment]
事件正常触发.

> 每个玩家本地也会创建其它玩家的“虚拟UI”

#137 之前的问题可能与之有关, lua创建的物品/技能ui没有创建虚拟ui导致其他玩家无法操作?

> 可能是bug, 问问引擎的? 1.0我记得没这个问题.

看了 #137 , 1.0应该也是有这个问题, 记错了

**Comment by sumneko** [comment]
> #137 之前的问题可能与之有关, lua创建的物品/技能ui没有创建虚拟ui导致其他玩家无法操作?

嗯，这个是引擎的bug，已经在修了。这个警告应该也是bug
