### ISSUE TITLE
支持传参后的ui event在获取data.data时报错

### ISSUE THREAD

**Issue by MouJiaoZi** [y3-editor/y3-lualib#178]
之前正常，更新至最新的“[修复报错](https://github.com/y3-editor/y3-lualib/commit/6551a294900bd599c007f0af26951619c49af3c8)”后报错

**Comment by sumneko** [comment]
你用的1.0编辑器还是2.0编辑器？

**Comment by sumneko** [comment]
报错截图和对应的代码截图看一下

**Comment by MouJiaoZi** [comment]
> 报错截图和对应的代码截图看一下

add_event('点击-结束', 'EVENT_NAME', { id: index })

事件响应那边读取的data.data.id

报错为attemp to index a nil value (field 'data')

之前正常，在fetch最新的commit后报错

**Comment by MouJiaoZi** [comment]
测试了下，回滚[最新的commit](https://github.com/y3-editor/y3-lualib/commit/6551a294900bd599c007f0af26951619c49af3c8)后正常运作

**Comment by sumneko** [comment]
请将分支切换到 `1.0`
