### ISSUE TITLE
造成伤害无跳字

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#181]
版本: 2.0
eca正常跳字, lua无跳字

**Comment by xuhuanzy** [comment]
话说发新版没测lua？那lua作图有意义吗？
如果是已发布的图撞上这种bug，那不是纯纯的暴死

**Comment by sumneko** [comment]
这个功能以前是正常的吗？

**Comment by xuhuanzy** [comment]
肯定正常啊, GameAPI.apply_damage, 单位造成伤害函数

**Comment by sumneko** [comment]
好像是这个API的跳字参数语义被改了，我需要去和相关人员确认一下。
如果确实是改了而且没有做好兼容性处理的话，流程确实是有问题的。

**Comment by sumneko** [comment]
明天的版本会修复

**Comment by xuhuanzy** [comment]
调试器的问题呢

**Comment by xuhuanzy** [comment]
已修复
