### ISSUE TITLE
“界面-消息”事件报错

### ISSUE THREAD

**Issue by lanchengkai** [y3-editor/y3-lualib#19]
1.界面-消息（ET_TRIGGER_COMPONENT_EVENT），鼠标进入/鼠标离开两个事件会报以下两个错误，注释掉后就正常使用，推测是事件对应值返回为空
    -- [4] = {
    --     name = "__pos",
    --     type = "py.Vector2",
    --     lua_name = "pos",
    --     lua_type = "py.Vector2",
    --     desc = "触碰坐标",
    --     lua_desc = "触碰坐标",
    -- },
    -- [5] = {
    --     name = "__touch_id",
    --     type = "integer",
    --     lua_name = "touch_id",
    --     lua_type = "integer",
    --     desc = "触碰ID",
    --     lua_desc = "触碰ID",
    -- },
![image](https://github.com/y3-editor/y3-lualib/assets/62948104/0b82a0b4-7cc3-45d3-acbc-eef9bdd4540c)

2.事件分发好像也有问题，注册一个事件是正常的，只会出现一条消息，但是注册两个事件当触发某一事件就会一并触发，
不确定其他带参数事件触发是否也如此
![image](https://github.com/y3-editor/y3-lualib/assets/62948104/681bacb4-a319-48f1-a0db-6b935a6d0641)

3.另外提一个警告的问题：这个小问题，不影响代码运行，但是可能普遍存在，强迫症难受
事件 玩家-加入游戏 是不需要带player参数的，但是实际情况是会有一个警告，需要把
gameevent.lua:
---@field event fun(self: self, event: "玩家-加入游戏", player: Player,  callback: fun(trg: Trigger, data: EventParam.玩家-加入游戏)): Trigger
改成
---@field event fun(self: self, event: "玩家-加入游戏", callback: fun(trg: Trigger, data: EventParam.玩家-加入游戏)): Trigger

**Comment by sumneko** [comment]
问题1与问题2可以提供一张演示图吗？

**Comment by lanchengkai** [comment]
[BugReport.zip](https://github.com/y3-editor/y3-lualib/files/12026516/BugReport.zip)
另外：新的版本中，虽然多人模式不报错了，但是事件不触发了。

**Comment by sumneko** [comment]
> 但是事件不触发了。

我测试是正常的，你用的什么事件？

**Comment by lanchengkai** [comment]
> 
就是压缩包里的这些，平台版本是1.2.28.627904

你试试“细节-玩家”里把第二个玩家调出来，再启动，调试时点两个玩家。

刚刚只有一个玩家我直接运行是正常的，但是把第二个玩家调出来后又不行了，现在再改回一个玩家也不触发了。

**Comment by lanchengkai** [comment]
> 我测试是正常的，你用的什么事件？

就是压缩包里的这些，平台版本是1.2.28.627904

你试试“细节-玩家”里把第二个玩家调出来，再启动，调试时点两个玩家。

刚刚只有一个玩家我直接运行是正常的，但是把第二个玩家调出来后又不行了，现在再改回一个玩家也不触发了。

**Comment by lanchengkai** [comment]
> 我测试是正常的，你用的什么事件？

重启后又正常了，这点我再测试。
找到规律再上报。

**Comment by sumneko** [comment]
> > 我测试是正常的，你用的什么事件？
> 
> 重启后又正常了，这点我再测试。 找到规律再上报。

好，麻烦你了~

**Comment by lanchengkai** [comment]
> 找到规律再上报。

其实原因来自 问题1，多人模式中不报警（此前忽略了这点），出错后后续代码不运行看起来就像是不触发。[笑哭]

**Comment by sumneko** [comment]
带参数的事件分发确实有问题，我明天改
