### ISSUE TITLE
使用代码操作ui时（创建、删除）同时进行随机数操作，有几率导致随机数序列出现偏差进而导致不同步

### ISSUE THREAD

**Issue by MouJiaoZi** [y3-editor/y3-lualib#193]
操作流程：
1.双开测试
2.y3.game.event 界面消息监听一个UI事件
2.玩家1点击UI，触发监听的事件
3.进行几个随机数相关操作
4.将随机数和玩家id编入event data中，使用y3.game.event.dispatch广播事件
5.所有客户端接受到广播的事件，与data中玩家id相匹配的客户端根据随机数内容进行UI创建、修改

步骤3中打印随机数有几率看到随机数列错位
所有操作除5的ui相关外均没有涉及本地玩家运算

**Comment by sumneko** [comment]
第5步使用的是第3步产生的随机数？

**Comment by MouJiaoZi** [comment]
> 第5步使用的是第3步产生的随机数？

第三步print随机数时已经出现偏移了

**Comment by sumneko** [comment]
> > 第5步使用的是第3步产生的随机数？
> 
> 第三步print随机数时已经出现偏移了

因为我看你的描述有可能是异步调用了获取随机数。获取随机数这个方法必须同步调用。

**Comment by MouJiaoZi** [comment]
> > > 第5步使用的是第3步产生的随机数？
> > 
> > 
> > 第三步print随机数时已经出现偏移了
> 
> 因为我看你的描述有可能是异步调用了获取随机数。获取随机数这个方法必须同步调用。

UI点击事件引发事件响应，事件响应调用另一个函数，仅将触发玩家id做参数，这应该不是不同步的调用吧，所有玩家都会收到UI事件以及触发UI事件的玩家

**Comment by sumneko** [comment]
> 所有操作除5的ui相关外均没有涉及本地玩家运算

我想知道你这里涉及本地玩家运算是哪一部分，里面有没有调用获取随机数

**Comment by MouJiaoZi** [comment]
> > 所有操作除5的ui相关外均没有涉及本地玩家运算
> 
> 我想知道你这里涉及本地玩家运算是哪一部分，里面有没有调用获取随机数

简单点说，在所有y3.game.event处进行print，所有客户端均同步print了，所有逻辑运算也没有id == local_player的判断

**Comment by MouJiaoZi** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/25788578/8224b431-ed89-40b8-b4c6-54d8bf8ab0bd)
该情况可能发生在所有通过代码对UI进行操作的时候
所有操作流程均为   玩家点击UI触发事件->响应事件进行逻辑处理->发出另一事件通知特定或所有玩家更新UI（设置文本、图片等）

**Comment by sumneko** [comment]
这个问题你解决了？

**Comment by MouJiaoZi** [comment]
> 这个问题你解决了？

是的，解决了，是在本地逻辑内调用了触发器导致的，但是真的全程没有随机数的参与
