### ISSUE TITLE
神奇BUG

### ISSUE THREAD

**Issue by 3145544645** [y3-editor/y3-lualib#195]
![6abe8711dd1de5aa7c9783ba3a270366](https://github.com/y3-editor/y3-lualib/assets/32957123/47fc99b1-9098-4062-8da9-d860899a1787)
![4d9e308d6810c6dde63b51fe166ea156](https://github.com/y3-editor/y3-lualib/assets/32957123/7f94bba8-56e8-4bfd-99d3-6ca0e76e639e)

**Comment by sumneko** [comment]
不算是bug，浮点数、定点数无法精确表示十进制数字 `0.2` 导致的。
扩展阅读：https://zhuanlan.zhihu.com/p/103254614
