### ISSUE TITLE
所谓的 Lua的数字由于浮点数误差问题可能会造成客户端之间不同步

### ISSUE THREAD

**Issue by w4454962** [y3-editor/y3-lualib#2]
是因为dll/exe 在编译的时候 浮点模型没有用 最严格的 /fp:strict  编译参数。  没有严格准守IEEE754标准产生的问题。 跟lua无关 要在脚本里解决这个问题太蠢了

**Comment by sumneko** [comment]
这个我会反馈给程序，不过据我所知，即使使用了这个参数依然无法保证跨平台时浮点数运算的一致性。

**Comment by w4454962** [comment]
没有严格准守IEEE754标准产生的问题， 像魔兽在早期各种cpu处理器还不统一的年代 在c++代码里内嵌了一套 ieee754的浮点数类 用来处理统一的浮点数计算。

**Comment by sumneko** [comment]
目前的解决方案也和魔兽那个类似，会将Lua虚拟机的Number实现改为自己的定点数实现，对于用户来说无感

**Comment by w4454962** [comment]
反正不是lua的问题，不在脚本层处理就行， 脚本层封装浮点数类 那点性能直接玩完
