### ISSUE TITLE
怎么创建一个魔法效果并添加到单位身上？

### ISSUE THREAD

**Issue by ocpam** [y3-editor/y3-lualib#205]
1. 想请问如何创建一个 buff魔法效果实例，翻了API没有发现有类似create的接口，unit和item啥的都有，
2. 关于添加魔法效果，unit:add_buff 需要一个Buff.AddData，也不知道怎么创建，本人lua新手不是很懂，请大佬赐教。

**Comment by sumneko** [comment]
1. 使用 `Unit:add_buff`
2. VSCode安装Lua插件，会有提示
![image](https://github.com/y3-editor/y3-lualib/assets/5213431/75173f8e-70b4-4a35-8057-f3bcb0259b55)

**Comment by ocpam** [comment]
好的，谢谢大佬！
