### ISSUE TITLE
获取父控件, 应该返回nil或者空控件, 而不应该报错

### ISSUE THREAD

**Issue by ChNopx** [y3-editor/y3-lualib#211]

**Comment by sumneko** [comment]
应该只有根节点的控件没有父控件吧，我觉得这个是使用时应当自己避免的

**Comment by ChNopx** [comment]
> 应该只有根节点的控件没有父控件吧，我觉得这个是使用时应当自己避免的

是的, 这个是我没描述清楚,  这个还是建议修复以下, 毕竟到底有没有父控件, 还是得获取一下,才知道, 万一是根节点, 没有父控件就直接报错了.

我现在是所有根节点命名都加了统一标识, 遍历获取父控件的时候, 获取下名称, 如果有根节点标识, 则直接返回nil, 避免报错
