### ISSUE TITLE
无法调试源代码

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#216]
断点提示 `The source file has no line information.` 或 `The source file has no line information.`

**Comment by xuhuanzy** [comment]
调试器浮点数仍然不正确, 
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/9ed4f14e-a982-4c69-aacc-ef88b42a3c5b)

**Comment by sumneko** [comment]
> 断点提示 `The source file has no line information.` 或 `The source file has no line information.`

截图看看

**Comment by xuhuanzy** [comment]
已载入脚本找不到这个文件, 但断在可断点的地方是可以跟进去的.
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/8e8b07c1-83ce-4a84-92a6-e72456931089)

**Comment by sumneko** [comment]
文件里有中文变量名？

**Comment by xuhuanzy** [comment]
有, 但没有的有部分也进不去

**Comment by sumneko** [comment]
用编辑器模式启动的游戏吗？

**Comment by xuhuanzy** [comment]
> 用编辑器模式启动的游戏吗？

是的, 2.0的编辑器内运行

**Comment by xuhuanzy** [comment]
y3库他也没有加载完全

**Comment by xuhuanzy** [comment]
有没有可能是win11的锅
