### ISSUE TITLE
事实上目前的UI系统自带排版系统，可以直接让某个面板居中，不需要自己算。你先自己尝试一下？

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#22]
事实上目前的UI系统自带排版系统，可以直接让某个面板居中，不需要自己算。你先自己尝试一下？

_Originally posted by @sumneko in https://github.com/y3-editor/y3-lualib/issues/12#issuecomment-1630237236_
            很不习惯使用界面编辑器,这个api问题不会修复了？

**Comment by sumneko** [comment]
请在原issue中继续讨论
