### ISSUE TITLE
apply_damage 函数注解顺序不正确

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#23]
且按官方的eca以下是可选参数
![image](https://github.com/y3-editor/y3-lualib/assets/90585805/185be2f9-4653-41d1-a7a1-a1cd6522ca03)

**Comment by xuhuanzy** [comment]
apply_damage 能否控制必不暴击? 当技能作为普攻时, 这个函数内部会自己算暴击, 现在必须得在调用前后手动设定暴击率

**Comment by sumneko** [comment]
其实是因为这个API我还没整理到，Game里的API太多了，目前在搞别的
