### ISSUE TITLE
鼠标按钮事件无法获取按键值

### ISSUE THREAD

**Issue by lanchengkai** [y3-editor/y3-lualib#24]
![image](https://github.com/y3-editor/y3-lualib/assets/62948104/45c2bc43-b6f7-44d0-ac72-2d62360e364a)

这是代码，current_key值获取任有问题。
```
Class 'Game'
    :event('鼠标-按下', y3.const.MouseKey.LEFT, function(trg, data)
        print(data.current_key)
    end)
```

[BugReport.zip](https://github.com/y3-editor/y3-lualib/files/12038891/BugReport.zip)

**Comment by sumneko** [comment]
这个事件就是没有这个字段的，我之后会把他从文档里清除掉

**Comment by lanchengkai** [comment]
> 

我去提个建议，少了这个感觉怪怪的，还破坏了代码的美感。

**Comment by sumneko** [comment]
这个事件你注册的时候是要指定按键的，所以事件参数里的按键没有意义

**Comment by lanchengkai** [comment]
local function a(_,data) end

game:event('mousekeydown', left, a)
game:event('mousekeydown', right, a)

方便这样的情况，如果没有的话就要多写一层。

**Comment by sumneko** [comment]
```lua
for _, key in ipairs {left, right} do
    game:event('mousekeydown', key, function (_, data)
        print('key is ' .. key)
    end)
end
```

**Comment by lanchengkai** [comment]
对，就要多写这外面一层。  
嘿嘿强迫症，没事，这个问题关了吧，我去提一下。
也许会做，不做的话也有解决方式，挺好的。
