### ISSUE TITLE
M.comp_id 中 anyGetter 的安全访问被最近的更新回退后，使用 uid 创建场景 ui 和实例化元件报错

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#243]
#[https://github.com/y3-editor/y3-lualib/blob/main/object/scene_object/ui.lua](url)

M.comp_id 中 anyGetter 的安全访问被最近的更新回退后，使用 uid 创建场景 ui 和实例化元件报错

**Comment by sumneko** [comment]
我把安全访问挪到了

https://github.com/y3-editor/y3-lualib/blob/f8e1f70596c76e1492b9e3cfafa21d33e3ea84e1/init.lua#L115-L141

我测试并没有报错，你接个图看看呢？

**Comment by xiazhixi** [comment]
我们的问题，换了个方式测试过了，没有问题。感谢
