### ISSUE TITLE
UI 事件缺少

### ISSUE THREAD

**Issue by soybeanmilkg** [y3-editor/y3-lualib#244]
const.lua y3.Const.UIEvent 和 M.UIEventMap 是不是漏了“左键-点击“事件

**Comment by sumneko** [comment]
叫 "左键-按下" ，"点击" 的语义不太明确

**Comment by soybeanmilkg** [comment]
我理解的点击是在控件内按下然后在控件内抬起，才算是完成一次点击。
只是在控件按下或抬起都不算是完成一次点击。
在我简单测试之后，
事件"左键-抬起"，在我将鼠标移出控件后仍会触发，
不过事件 key '12', '30' 就比较符合我的预期，在控件内按下然后抬起才会触发，当我将鼠标移出控件再抬起就不会触发。
而且对于鼠标右键，我没有找到与"左键-抬起"类似的事件，"右键-抬起"和“右键-按住”都是在鼠标抬起后触发。
所以“右键-按住”和“左键-按住”这两个事件的触发时机都是不一样的。
