### ISSUE TITLE
跳字函数无法显示除数字外的字

### ISSUE THREAD

**Issue by 52charlang** [y3-editor/y3-lualib#249]
GameAPI.create_harm_text()和GameAPI.create_harm_text_ex()创建漂浮字时,内容只能是数字,
![F3C6](https://github.com/y3-editor/y3-lualib/assets/150227880/a1fce042-9c6f-42e5-9a24-4af00408abb8)
,尝试了很多次123w或其他格式,想实现类似123万这样的跳字效果都失败了,我不知道这是不是bug,还是底层没有实现,或是我不会用-_-

**Comment by sumneko** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/5213431/413942bf-2f71-4b6a-bb60-8f55fc4230d6)

请使用此配置
