### ISSUE TITLE
class 重载会误报循环继承错误

### ISSUE THREAD

**Issue by ChNopx** [y3-editor/y3-lualib#281]
local a = Class 'c1'

local b = Class 'c2'
Extends('c2', 'c1')

local c = Class 'c3'
Extends('c3', 'c2')

-- 如果new 过实例, 重载就不会循环引用
local d = New 'c3' ()

--如果没有new 实例, 重载就报循环继承错误

**Comment by sumneko** [comment]
我无法复现这个问题，你再确认一下代码？
