### ISSUE TITLE
有没有y3-lualib完成项目

### ISSUE THREAD

**Issue by 314599782** [y3-editor/y3-lualib#284]
有没有y3-lualib完成项目 ,能与Npc购买物品，能打怪，胜利失败判断

**Comment by 314599782** [comment]
demo里面就一个刷怪，能不能把每种使用方法都写个示例。
比如 怪死亡掉落物品 我不会写了

**Comment by sumneko** [comment]
> demo里面就一个刷怪，能不能把每种使用方法都写个示例。 比如 怪死亡掉落物品 我不会写了

这个可以使用全局事件“单位-死亡”，事件触发后根据设计创建物品在地上即可。

**Comment by 314599782** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/13996502/fbe0ce6d-2ab1-42f7-a5cb-452b04a0d182)
在商店里安装了一个lualib ui插件 ，我也没找到触发器 也没看到代码 他怎么绑定数据的

**Comment by 314599782** [comment]
eca的GameHUD ui包括背包 ，物品栏 可以用lualib做一份吗 。

**Comment by sumneko** [comment]
> eca的GameHUD ui包括背包 ，物品栏 可以用lualib做一份吗 。

这个做好了，我一直忘了上传，明天传一下

**Comment by 314599782** [comment]
英雄背包物品右键不能移动位置

**Comment by 314599782** [comment]
eca中的触发器查看lua代码
-- local trigger1 = y3.game:event({const.GlobalEventType.MOUSE_D_CLICK_UNIT,const.MouseKey.LEFT}, function(_, data)
-- 	if not y3.all_conditions_succeed({data.unit:has_tag('选人'), y3.call_any_api_2('get_kv_pair_value_unit_name', data.player.base(), '选择英雄') == nil})then
-- 		return
-- 	end
我想把这个代码转为lua
y3.game:event('本地-鼠标-双击单位',y3.const.MouseKey['LEFT'],function (trg,data)
    if data.unit:has_tag('选人') then
        GameAPI.get_kv_pair_value_unit_name(data.player., '选择英雄')
    end
    
end)

data.player没有base方法 请问怎么弄
