### ISSUE TITLE
mover报错

### ISSUE THREAD

**Issue by baiyuek** [y3-editor/y3-lualib#29]
---@type Projectile.CreateData
    local data = {}
    data.ability = abilityEvd.ability
    data.key = 134281805
    data.owner = abilityEvd.unit
    data.height = 50
    data.target = y3.unit.get_point(abilityEvd.unit)
    local pt = y3.projectile.create(data)
    
    ---@type Mover.CreateData.Target
    local mover_data ={}
    mover_data.ability = abilityEvd.ability
    mover_data.target = abilityEvd.target
    mover_data.speed = 1000
    mover_data.hit_same = false
    mover_data.height = 50
    mover_data.face_angle = true
    mover_data.max_distance = 5000
    mover_data.acceleration = 0
    mover_data.hit_radius = 50
    mover_data.hit_type = 1
    mover_data.is_absolute_height = false
    mover_data.max_speed = 2000
    mover_data.min_speed = 800
    mover_data.parabola_height = 100
    mover_data.priority = 1
    mover_data.terrain_block = false
    mover_data.on_hit =function (mover)
        hm.damage.attack(abilityEvd.unit,abilityEvd.target,abilityEvd.ability)
    end
    y3.mover.mover_target(pt,mover_data)

报错如下：
[2023-07-16-17-24-34] : [Error]: [error] error during Python call
stack traceback:
	[C]: in field 'set_mover_relate_ability'
	...LocalData/wxsj/script/y3\object\runtime_object\mover.lua:150: in function 'y3.object.runtime_object.mover.init'

如果不设置mover_data.ability倒是不再报错，但是似乎也没有效果

**Comment by baiyuek** [comment]
可以优先修复吗  没法做远程攻击和技能了

**Comment by sumneko** [comment]
> 可以优先修复吗 没法做远程攻击和技能了

今天搞定
