### ISSUE TITLE
复刻官方技能教程的过程中卡在了创建投射物

### ISSUE THREAD

**Issue by Armingers** [y3-editor/y3-lualib#291]
复刻官方技能教程的过程中卡在了创建投射物
-- 这是第一步 event在API文档写的很清晰 然后行为需要的method也很清楚
![ECA1](https://github.com/y3-editor/y3-lualib/assets/100256770/2ffc412c-4f51-4ccb-846b-5027f5d60d12)
![lua1](https://github.com/y3-editor/y3-lualib/assets/100256770/4744aef2-d67e-4347-b735-48e7486ba3a2)
第二步 创建投射物
![ECA2](https://github.com/y3-editor/y3-lualib/assets/100256770/adca4131-a5a2-4e89-ad7b-59b007c584fb)
![Lua2](https://github.com/y3-editor/y3-lualib/assets/100256770/9bd1888a-d549-47a9-a196-3e24029064c6)
![lua4](https://github.com/y3-editor/y3-lualib/assets/100256770/3d46e3c0-b0cb-4dc7-9143-70d20efcade1)
只找到了相关function和底层lua 
请问这个Projectile.CreateData 里的数据是什么？第一个值我输入物编里的投射物ID显示不对
还是现在lua没有完善投射物这个功能？
望解答谢谢
ps：希望多出一些基本教程

**Comment by sumneko** [comment]
> 请问这个Projectile.CreateData 里的数据是什么？第一个值我输入物编里的投射物ID显示不对

需要传入一张表
