### ISSUE TITLE
lublib更新问题

### ISSUE THREAD

**Issue by tyhlovecm** [y3-editor/y3-lualib#294]
我之前的lualib用的是3.15号的  今天26号更新之后发现有些物品相关的方法报错

比方item:use_item

unit:shift_item

![image](https://github.com/y3-editor/y3-lualib/assets/24623815/667e4157-985d-486e-bec1-e793b00b57de)

**Comment by sumneko** [comment]
应该不是LuaLib的问题？你回退到之前的版本有这个问题吗
