### ISSUE TITLE
Mover.CreateData.Round中的round_time无效，以及on_finish回调不会触发

### ISSUE THREAD

**Issue by Zui0** [y3-editor/y3-lualib#298]
1、Mover.CreateData.Round中的round_time无效，无论设置多少数值运动器效果都一直存在
2、projectile:mover_round()的on_finish回调不会触发，不确定是否因为上面的问题导致

**Comment by sumneko** [comment]
1. round_time 指的是转一圈所需的时间
2. 环绕运动应该确实是没有完成事件，我把它去掉

**Comment by Zui0** [comment]
1、如果round_time 指的是转一圈所需的时间，那么是否与angle_speed环绕速度的作用重复了，都是用来控制环绕一圈的速度的
2、如果round_time不是指运动器环绕时间，好像没有找到其他可以控制时间参数，而且ECA的环绕运动器提供了环绕时间这个参数
