### ISSUE TITLE
建议出个eca转lua代码对照表

### ISSUE THREAD

**Issue by 314599782** [y3-editor/y3-lualib#299]
eca有个查看lua代码的功能很实用，用来学习纯lua代码很好 ，现在纯lua写法教程太少，只能通过这种方法慢慢弄。
但是有很多方法不知道如何替换

比如eca转lua后得代码是

local trigger1 = y3.game:event({const.GlobalEventType.MOUSE_D_CLICK_UNIT,const.MouseKey.LEFT}, function(_, data)
	if not y3.all_conditions_succeed({data.unit:has_tag('选人'), y3.call_any_api_2('get_kv_pair_value_unit_name', data.player.base(), '选择英雄') == nil})then
		return
	end
	data.unit:change_owner(data.player)
	data.unit:blink(y3.get_point_by_scene_id(10001))
	y3.camera.linear_move_by_time(data.player, y3.get_point_by_scene_id(10001), 1.0, const.CameraMoveMode.ACC)
	data.player:select_unit(data.unit)
	y3.call_any_api_3('add_unit_entity_kv', data.player.base(), '选择英雄', data.unit.base())
end)

我花了好大精力才弄好

--选人
y3.game:event('鼠标-双击单位',y3.const.MouseKey['LEFT'],function (trg,data)
    if data.unit:has_tag('选人') then
        if not data.player:kv_has('选择英雄') then
            data.unit:change_owner(data.player)
            data.unit:blink(y3.point.get_point_by_res_id(10001))
            y3.camera.linear_move_by_time(data.player, y3.point.get_point_by_res_id(10001), 1.0, y3.const.CameraMoveMode.ACC)
            data.player:select_unit(data.unit)
            data.player:kv_save('选择英雄',data.unit)
        end
    end
    
end)

其实大部分函数名称差不多可以直接找到，但是有小部分可能不太一样，对于老手来说很容易，对于新手很是头疼，如果有个文档或者几十个示例 ，那lualib肯定容易推广很多

**Comment by sumneko** [comment]
在搞了，只是工程量有点大

**Comment by 314599782** [comment]
先出个好用一点的api文档吧，归归类，代码里那个文档太不方便看了吧 ，每个api写个示例 。这个项目就有质的飞升了。不然很难用啊

**Comment by 314599782** [comment]
方正现在我可以倒着玩了 ，lua源码我都能编译了 ，文档不文档我无所谓 ，新人难吧
