### ISSUE TITLE
y3.game.event() 报错

### ISSUE THREAD

**Issue by codediy** [y3-editor/y3-lualib#3]
![image](https://github.com/y3-editor/y3-lualib/assets/20250924/98d2b85f-b640-4002-a306-50f4d0a482ac)

![image](https://github.com/y3-editor/y3-lualib/assets/20250924/8702cfbe-48c6-42fd-90f9-d0a7688be2c6)

![image](https://github.com/y3-editor/y3-lualib/assets/20250924/970f29fd-f3f8-4fbe-960c-e65028426046)

**Comment by codediy** [comment]
添加了一段修复代码。
![image](https://github.com/y3-editor/y3-lualib/assets/20250924/47965cab-8347-4d85-bd26-1f4fbaeb17aa)
这下面还会报错 
![image](https://github.com/y3-editor/y3-lualib/assets/20250924/fcfa00cc-c872-4654-9ce0-8d2ecef0ddf0)

![image](https://github.com/y3-editor/y3-lualib/assets/20250924/2442f7e9-b981-4793-ac1d-0e44327fb904)

大概是事件名称对不上
![image](https://github.com/y3-editor/y3-lualib/assets/20250924/972fc6ac-1529-4c94-9c55-bcb2f3e379dc)

![image](https://github.com/y3-editor/y3-lualib/assets/20250924/e3accc0e-3ad6-4abc-a612-5452dbbd6e68)

**Comment by sumneko** [comment]
fixed by 11439afb328088ef4d807279e281432a73ac0640
