### ISSUE TITLE
多层继承报错

### ISSUE THREAD

**Issue by lanchengkai** [y3-editor/y3-lualib#30]
local A = Class 'A'

function A:constructor()
end

local B = Class('B', 'A')

function B:constructor()
    Super(self)() ---卡死
end

local C = Class('C', 'B')

function C:constructor()
    Super(self)()
end

New 'C' () --- 无法继承第三层 中间会卡死 死循环了

BTW local player = Class 'Game'.get_client_player() --- y3.game.player 报错 没有赋值

**Comment by lanchengkai** [comment]
[2023-07-17-20-15-48] : [Error]: Traceback (most recent call last):
LuaError: [string "<python>"]:7: bad argument #2 to 'origin_string_format' (value has no literal form)
stack traceback:
	[C]: in function 'origin_string_format'
	[string "<python>"]:7: in function 'string.format'
	...es/y3/game/LocalData/BugReport/script/y3\tools\class.lua:92: in function 'y3.tools.class.super'
	...han/Games/y3/game/LocalData/BugReport/script/gm/init.lua:17: in field 'constructor'
	...es/y3/game/LocalData/BugReport/script/y3\tools\class.lua:24: in function <...es/y3/game/LocalData/BugReport/script/y3\tools\class.lua:20>
	...han/Games/y3/game/LocalData/BugReport/script/gm/init.lua:21: in main chunk
	[C]: in function 'require'
	[string "<python>"]:2: in main chunk

新版本报错

**Comment by lanchengkai** [comment]
虽然不报错了，Super()参数变成了字符串，感觉有点怪怪的。不方便。
建议能改回Super(self)
另外部分事件失效了，已知的有“鼠标-按下””鼠标-抬起”等鼠标事件，界面-消息。

**Comment by sumneko** [comment]
> 虽然不报错了，Super()参数变成了字符串，感觉有点怪怪的。不方便。
> 建议能改回Super(self)

做不了，否则没法知道是谁的super，之前死循环就是因为参考的`self`，但`self`的类型是C所以一直在调用B。

**Comment by sumneko** [comment]
> 另外部分事件失效了，已知的有“鼠标-按下””鼠标-抬起”等鼠标事件，界面-消息。

开个新issue
