### ISSUE TITLE
最新版本部分事件失效，已知的有“鼠标-按下””鼠标-抬起”等鼠标事件，“界面-消息”。

### ISSUE THREAD

**Issue by lanchengkai** [y3-editor/y3-lualib#31]
RT

**Comment by holyalice1990** [comment]
使用 T转lua 的接口  y3.game:event({y3.const.GlobalEventType.UI_EVENT,y3.game.str_to_ui_event("鼠标点击2")}, function(_, data)   lua环境下 无法触发  
但是T 可以
