### ISSUE TITLE
绑定单位属性BUG

### ISSUE THREAD

**Issue by Mtp719** [y3-editor/y3-lualib#317]
给进度条绑定单位属性时，显示的进度值不正确，比如当前值50，最大值100，进度显示的依旧是100%，我用ECA测了一下没有问题，在lua不行

**Comment by sumneko** [comment]
看看你的代码，我这边的demo里是正常的，见 `y3\演示\demo\界面\主控.lua`

**Comment by Mtp719** [comment]
已经解决了。。原来要绑定子控件
