### ISSUE TITLE
如何获得物品技能目标

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#318]
需求：假设一个物品叫<吞噬丹>，并且<吞噬丹>有一个主动技能，对其他物品使用后，如果符合释放条件就会吞噬目标物品，然后删掉<吞噬丹>

问题：
1.在物品-使用事件内如何取到目标物品/单位
2.如何在技能-施法出手内取到来源物品

上面需求是现在防守图基本必备的功能

**Comment by sumneko** [comment]
自己记一下最后使用的物品
