### ISSUE TITLE
几个物品需求

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#319]
1.希望区分一下物品name和title
需求场景：
item:set_name(item.title)，这样就可以给地上的物品名字和物品tip设置带颜色的title，但是当get_name时返回的确是带颜色的title，希望能返回name

2.充能型物品新增<使用消耗次数>，目前是能通过卡BUG的方式生效。。。先把物品设置成<堆叠>，然后修改<使用消耗次数>后再改回充能型，就会生效了，希望能直接开放修改
需求场景：
比如一个物品杀敌会增加充能层数，达到100层后点击使用这个物品可以获得奖励，并且点击物品时不能消耗充能层数（目前会消耗）
如果用堆叠型就会有问题，比如再次获得这个物品就叠加了，这是不合理的。。

3.增加事件 物品-即将获得
需求场景：一些物品如果不合符条件是不允许拾取的，比如属于其他玩家的物品，尤其是自动使用的物品和堆叠型物品

**Comment by ldoubil** [comment]
物品-即将获得 这个有不过是在命令里面

**Comment by sumneko** [comment]
听起来和这个LuaLib库无关，功能需求请按照issue引导提到论坛或QQ群
