### ISSUE TITLE
选中BUG

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#322]
1.选中-单位事件，先左键单击选中一个单位，然后在<重新>框选1个单位（只框选1个）那么get_selecting_unit获取到的依旧是上一个单击选中的单位，建议框选时如果单位组只有一个单位时也触发选中单位事件

2.选中-取消未生效：我测试杀死/删除选中的单位没有触发事件，物品也一样

**Comment by sumneko** [comment]
> 1.选中-单位事件，先左键单击选中一个单位，然后在<重新>框选1个单位（只框选1个）那么get_selecting_unit获取到的依旧是上一个单击选中的单位，建议框选时如果单位组只有一个单位时也触发选中单位事件

无法复现


> 2.选中-取消未生效：我测试杀死/删除选中的单位没有触发事件，物品也一样

主动操作才算取消，死掉的单位还是选中的（参考Dota2的效果）

**Comment by padoruuu** [comment]
> > 1.选中-单位事件，先左键单击选中一个单位，然后在<重新>框选1个单位（只框选1个）那么get_selecting_unit获取到的依旧是上一个单击选中的单位，建议框选时如果单位组只有一个单位时也触发选中单位事件
> 
> 无法复现
> 
> > 2.选中-取消未生效：我测试杀死/删除选中的单位没有触发事件，物品也一样
> 
> 主动操作才算取消，死掉的单位还是选中的（参考Dota2的效果）

表达错误，是框选1个单位时没有触发选中-单位，我自己在判断下单位组吧
