### ISSUE TITLE
怎么通过 py.ItemKey获取物品

### ISSUE THREAD

**Issue by 314599782** [y3-editor/y3-lualib#327]
我找遍了函数 也没找到能够通过 py.ItemKey获取Item的方法。
商店列表返回的是ItemKey，我没法得到Item

**Comment by 314599782** [comment]
我理解的是 物品类型 是 物品的一种模板 还没创建成物品 应该获取不到

**Comment by sumneko** [comment]
`y3.object.item[ItemKey].data` 可以获取物编数据

**Comment by 314599782** [comment]
取出来是个userdata数据应该怎么用呢
