### ISSUE TITLE
单位属性绑定血条无效

### ISSUE THREAD

**Issue by tyhlovecm** [y3-editor/y3-lualib#334]
![image](https://github.com/y3-editor/y3-lualib/assets/24623815/ac91ad05-ac9f-435f-aa1c-4c81deb7a5fe)

**Comment by sumneko** [comment]
检查一下你的 `hp_container` 类型是进度条吗

**Comment by tyhlovecm** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/24623815/421d1ad0-cdf4-4c4a-ab15-74b739001307)
绑定了

**Comment by tyhlovecm** [comment]
> 检查一下你的 `hp_container` 类型是进度条吗

看上面，绑定了

**Comment by Mtp719** [comment]
要绑定progress_bar_img

**Comment by tyhlovecm** [comment]
> progress_bar_img

可以了  谢谢
