### ISSUE TITLE
filter_unit_id_list_in_area_v2 无法找到目标，但是filter_unit_id_list_in_area可以

### ISSUE THREAD

**Issue by birnfly** [y3-editor/y3-lualib#335]
python_len(GameAPI.filter_unit_id_list_in_area(y3.point.create(0,0).handle,y3.shape.create_circular_shape(10000).handle))
python_len(GameAPI.filter_unit_id_list_in_area_v2(y3.point.create(0,0).handle,y3.shape.create_circular_shape(10000).handle))

![image](https://github.com/y3-editor/y3-lualib/assets/7858384/bc917ff6-06a5-4887-914b-f2df1de74af0)

**Comment by sumneko** [comment]
请使用

```lua
local unit_group = y3.selector.create()
    : in_shape(y3.point.create(0,0), y3.shape.create_circular_shape(10000))
    : get()

print(unit_group:count())
```

很多底层API对具体参数有一些特别的限制，比如这个某个位置的参数必须要传值不能省略。所以尽量不要自己裸调用GameAPI。
