### ISSUE TITLE
增加参数提示

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#340]
像
---获取技能类型字符串属性
---@param ability_key py.AbilityKey 技能类型id (物编id)
---@param key py.AbilityStrAttr 键值key
---@return string str 值
function M.get_str_attr_by_key(ability_key, key)
    return GameAPI.get_ability_conf_str_attr(ability_key, key)
end
这个接口
py.AbilityStrAttr  类型 完全不知道改填入一个什么样的整数

**Comment by sumneko** [comment]
请改用 `y3.object.ability[ability_key].data` 来读表
