### ISSUE TITLE
对象事件疑问

### ISSUE THREAD

**Issue by Mtp719** [y3-editor/y3-lualib#341]
`local u1 = y3.unit.create_unit(y3.player(1), 134253745, y3.point(0,0), 0)
local u2 = y3.unit.create_unit(y3.player(1), 134253745, y3.point(0,0), 0)

y3.unit:event_on('测试事件2',function ()
    print('触发事件2')
end)

u1:event_on('测试事件1', function ()
    print('触发事件1')
end)

u2:event_on('测试事件1', function ()
    print('触发事件1')
end)

u1:event_notify('测试事件1')`

为什么注册了y3.unit事件后，会导致u1和u2都能收到测试事件1，是我写错了吗

**Comment by sumneko** [comment]
不应该使用 `y3.unit:event_on`
