### ISSUE TITLE
接口没有枚举类型

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#344]
---获取技能类型整数属性
---@param ability_key py.AbilityKey 技能类型id (物编id)
---@param key string 键值key
---@return integer value 值
function M.get_int_attr_by_key(ability_key, key)
    return GameAPI.get_ability_conf_int_attr(ability_key,key)
end

完全不知道这个 key 该填什么内容呀，输入单位属性名称 爆错，我看了y3转lua的代码 其实是有相应的英文单词的

**Comment by sumneko** [comment]
请改用 `y3.object.ability[ability_key].data` 来读表
