### ISSUE TITLE
技能组件问题

### ISSUE THREAD

**Issue by tyhlovecm** [y3-editor/y3-lualib#346]
技能绑定技能组件 默认是点击左键会释放，现在需要做技能的拖拽。拖拽的同时会释放。

 
没看到技能ui  去掉默认左键释放 或者我这边有什么别的方式可以实现吗

**Comment by sumneko** [comment]
只能自己重新实现点击功能了（比如可以盖一张透明的图片在按钮上方，自己处理点击这张图片）

**Comment by tyhlovecm** [comment]
> 只能自己重新实现点击功能了（比如可以盖一张透明的图片在按钮上方，自己处理点击这张图片）

好的  谢谢
