### ISSUE TITLE
在ECA物编单位下,有很多触发,但是在lua 物编中没有,只有on_create,on_dead,on_remove,其他触发需要针对某个具体的单位实例才行,能不能做得像ECA那样直接在物编里给所有这样的单位定义

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#354]
在ECA物编单位下,有很多触发,但是在lua 物编中没有,只有on_create,on_dead,on_remove,其他触发需要针对某个具体的单位实例才行,能不能做得像ECA那样直接在物编里给所有这样的单位定义

**Comment by sumneko** [comment]
我之后直接支持 `y3.object.unit[xxx]:event('单位-死亡', ...` 吧，可以一起批量生成

**Comment by ApolloHY** [comment]
对,类似这样的,比如受伤伤害结算前,结算后,单位升级,等等ECA里一系列在物编里直接定义的触发
还有技能那里也是的.某些触发只能针对某个具体的技能实例

**Comment by ApolloHY** [comment]
另外也建议在Y3开发助手里,增加更新lualib功能,不然每次都要初始化,初始化又害怕删除或者修改掉自己的一些文件.

**Comment by sumneko** [comment]
> 另外也建议在Y3开发助手里,增加更新lualib功能,不然每次都要初始化,初始化又害怕删除或者修改掉自己的一些文件.

![image](https://github.com/y3-editor/y3-lualib/assets/5213431/7bb85525-eaca-4473-aa85-e222aa186a67) VSCode左下角有同步按钮
另外初始化过一次以后，Y3开发助手里的初始化按钮是隐藏掉的，你是手动输入指令初始化的吗？

**Comment by ApolloHY** [comment]
我是使用F1里,选择初始化开发环境,,因为我之前用过这个功能,然后把自己的UI给刷掉了,换成了爆战兄弟的UI,所以印象很深.

**Comment by sumneko** [comment]
> 我是使用F1里,选择初始化开发环境,,因为我之前用过这个功能,然后把自己的UI给刷掉了,换成了爆战兄弟的UI,所以印象很深.

初始化后应该有提示，之前的 y3目录移至回收站

**Comment by ApolloHY** [comment]
哦,看到了,了解,感谢
