### ISSUE TITLE
设置网格列表启用/禁止滚动条 无效

### ISSUE THREAD

**Issue by lc12345** [y3-editor/y3-lualib#357]
--设置网格列表启用/禁止滚动条
---@param role py.Role # 玩家
---@param comp_uid string # 控件uid
---@param enable boolean # 是否启用
function GameAPI.set_ui_gridview_bar_enable(role, comp_uid, enable) end

这个是没有实装吗？

**Comment by lc12345** [comment]
attempt to call a nil value (field 'set_ui_gridview_scroll')

**Comment by sumneko** [comment]
看看ECA里有没有对应的，如果没有的话就是还没外放
