### ISSUE TITLE
关于Y3开发助手初始化的问题

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#361]
因为在script目录下,Y3助手窗口里没有命令,显示:There is no data provider registered that can provide view data.

然后我删除script,重新初始化后,完成会自动跳到script目录下,这个时候Y3助手里是有全部命令,以及物编数据的

但是退出VSCODE,重新打开之后,就没有,必须回到script上一级目录entrymap Y3助手视窗里才有命令,但是物编数据里也是没有,说叫我重新初始化,请问怎么解决.

**Comment by sumneko** [comment]
检查一下是否有 `clicli` 插件，有的话卸载掉

**Comment by ApolloHY** [comment]
原来如此,已解决,确实卸载就行了.
