### ISSUE TITLE
测试单位死亡 未移除场景ui

### ISSUE THREAD

**Issue by tyhlovecm** [y3-editor/y3-lualib#364]
![image](https://github.com/y3-editor/y3-lualib/assets/24623815/9b2219d8-b5e5-465d-bdf8-2a46fe8b5340)

![image](https://github.com/y3-editor/y3-lualib/assets/24623815/17656fac-dc2a-4cff-bde8-6baed5b49273)
测试单位死亡 未移除场景ui

**Comment by sumneko** [comment]
这个是单位移除才会删的，如果要死亡删可以注册一个触发器

**Comment by tyhlovecm** [comment]
> 这个是单位移除才会删的，如果要死亡删可以注册一个触发器

具体咋弄呢,好像没有相关方法

**Comment by sumneko** [comment]
```lua
data.unit:event('单位-死亡', function ()
    scene_ui:remove()
end)
```
