### ISSUE TITLE
关于GameAPI.get_role_real_mouse_x没有返回值

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#366]
要获取玩家的鼠标位置,但是文档里说必须要开启y3.config.sync.mouse = true
但是说开启后有额外的开销
于是找了这个方法
--界面-获取玩家鼠标真实x坐标
---@param role py.Role # 玩家
function GameAPI.get_role_real_mouse_x(role) end

但是这个方法没有返回值.

关于ECA里有获取玩家的鼠标方法,底层原理是一样的吗?还是游戏里默认开启了y3.config.sync.mouse = true?

**Comment by ApolloHY** [comment]
关于获取玩家鼠标位置,必须要开启
y3.config.sync.mouse = true
但是使用事件里的鼠标移动,同样也可以获取到鼠标位置,并且这里不需要开启y3.config.sync.mouse = true
这是为什么呢?
我使用鼠标移动事件监听每一名玩家的鼠标位置好还是开启y3.config.sync.mouse = true获取鼠标位置好?

**Comment by ldoubil** [comment]
纠结这个没有意义,性能差别微乎其微.你要用lua就一定会打开
y3.config.sync.mouse = true
y3.config.sync.camera = true

**Comment by sumneko** [comment]
> 关于ECA里有获取玩家的鼠标方法,底层原理是一样的吗?还是游戏里默认开启了y3.config.sync.mouse = true?

保存地图时编辑器发现你在ECA里用了获取鼠标位置，就会帮你设置 `y3.config.sync.mouse = true` 。Lua比较动态不好扫描，所以要你自己做。

> 我使用鼠标移动事件监听每一名玩家的鼠标位置好还是开启y3.config.sync.mouse = true获取鼠标位置好?

其实这2个是同一件事，后者帮你把前者做了。
