### ISSUE TITLE
关于标签的相关函数缺少

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#377]
能否增加一个获取 单位/物品/技能，已添加的标签内容

**Comment by liang-1-qi** [comment]
目前有个方法是 y3.object.ability[ability_key].data 获取 tags 但是这个返回的类型是 userdata

**Comment by liang-1-qi** [comment]
目前有个方法是 y3.object.ability[ability_key].data 获取 tags 但是这个返回的类型是 userdata

**Comment by sumneko** [comment]
直接 ipairs 这个userdata即可
