### ISSUE TITLE
运动器环绕运动器结束回掉没有效果

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#379]
ammo:mover_round({
                target = data.unit,
                radius = obj["环绕半径"],
                angle_speed = obj["弹道速度"],
                init_angle = 360/obj["弹药数量"] * (i-1.0),
                clock_wise = true,
                round_time = data.ability:get_float_attr("施法出手"),
                hit_type = 0,
                hit_radius = obj["基础弹药伤害范围"],
                hit_same = true,
                hit_interval = 0.06,
                ability = data.ability,
                on_finish = function (self)
                    print("结束了")
                    ammo:remove()
                end,
                on_break = function (self)
                    ammo:remove()
                end,
                on_hit = function (self, unit)
                    data.unit:damage({
                        target = unit,
                        type = '物理',
                        damage = math.random(data.ability:get_float_attr("技能伤害值")*0.8,data.ability:get_float_attr("技能伤害值")*1.5),
                        text_type = 'physics',
                        ability = data.ability
                    })
                end
            })
            我设置了 round_time  环绕时间，时间都到了，这个还在这个转，这个是个什么条件才会触发这个结束回调

**Comment by sumneko** [comment]
等6月27号运动器重构再看

**Comment by sumneko** [comment]
测试了一下已经会触发 on_finish 了
