### ISSUE TITLE
返回参数不对

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#38]
GameAPI.get_player_ui_pos_x(role)
GameAPI.get_player_ui_pos_y(role)

--玩家鼠标屏幕位置X
---@param role py.Role # 玩家
---@return integer # 鼠标屏幕位置X
function GameAPI.get_player_ui_pos_x(role) end

--玩家鼠标屏幕位置Y
---@param role py.Role # 玩家
---@return integer # 鼠标屏幕位置Y
function GameAPI.get_player_ui_pos_y(role) end

返还值拿到的永远是0,0

**Comment by sumneko** [comment]
我用 `y3.player(1):get_ui_pos_x()` 测试是正常的
