### ISSUE TITLE
获取技能名称返回 负数

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#382]
y3.object.ability[ability_key].data   获取name 为啥返回整数呢，这个该如何转换为 字符串名称

**Comment by liang-1-qi** [comment]
还有就是有的类型 是userdata 这个该如何处理成 table 呢

**Comment by sumneko** [comment]
使用 `y3.game.locale(name)` 转换，或是直接用 `y3.unit.get_name_by_key(unit_key)`

**Comment by sumneko** [comment]
userdata 可以直接当 table 读字段
