### ISSUE TITLE
EditorObject相关问题

### ISSUE THREAD

**Issue by kneesbuster** [y3-editor/y3-lualib#386]
![image](https://github.com/y3-editor/y3-lualib/assets/34144187/1da2b023-e11e-4773-83b3-50f995944ce1)
能否把TriggerData全量传入subscribe?
比如item:on_lose，需要知道是哪个单位失去了物品
此时item:get_owner()为nil，只能在trigger的data.unit能取到
![image](https://github.com/y3-editor/y3-lualib/assets/34144187/ceec267e-4b53-4d24-b685-d023c5112827)
再如这种需要多个字段的情况，但callMethod目前仅支持传入两个参数

**Comment by sumneko** [comment]
这个写法已经废弃了，直接用 `y3.object.item[123]:event('物品-失去', function (trg, data) end)` 就好了

**Comment by kneesbuster** [comment]
受教了！
建议有空把演示里面那个写法改了吧hhh
