### ISSUE TITLE
使用 播放魔法效果表现到模型控件异常

### ISSUE THREAD

**Issue by tyhlovecm** [y3-editor/y3-lualib#387]
![image](https://github.com/y3-editor/y3-lualib/assets/24623815/a3374411-253e-4a72-8d5c-4d1d17218220)
![image](https://github.com/y3-editor/y3-lualib/assets/24623815/e85b1c7b-d955-4831-a3c1-ae7ef52990bc)
![image](https://github.com/y3-editor/y3-lualib/assets/24623815/e80c7492-c314-4bbe-b8f4-1e63ff3c8140)

![image](https://github.com/y3-editor/y3-lualib/assets/24623815/8e78b3a7-655e-4838-a79d-cc98a8e0d8c5)

做了个魔法效果，头发挂接到头上。

选角页面，调用set_modifier_on_ui_model，头发会掉到地上  有时候又正常

**Comment by sumneko** [comment]
试一下用ECA正常吗？

**Comment by tyhlovecm** [comment]
> > 试一下用ECA正常吗？
> 
> ![1717652216452](https://private-user-images.githubusercontent.com/24623815/337132031-b9bfcf54-524e-4791-9928-92e04a9aaccf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTI1NjksIm5iZiI6MTcxNzY1MjI2OSwicGF0aCI6Ii8yNDYyMzgxNS8zMzcxMzIwMzEtYjliZmNmNTQtNTI0ZS00NzkxLTk5MjgtOTJlMDRhOWFhY2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA1Mzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTFhZjRiNmZkZDQ1MjUyZGY2NWM5YjQ3OWM2NGQyMTY4NTFlZDY4ZjQ4MWUwY2I5NTQ4MGIyMTM5ZDA4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nq5ua6dIg1vfzQ2C358vN7c3dpn9wbEAJDFVAX7XME8) 刚测试 也不对

![image](https://github.com/y3-editor/y3-lualib/assets/24623815/2bd44bdf-e363-4f07-b211-d3345f436dfb)

**Comment by sumneko** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/5213431/bb83402b-6594-4189-948b-fb9aaa048965)

要启用这些可选参数

**Comment by tyhlovecm** [comment]
> ![image](https://private-user-images.githubusercontent.com/5213431/337188668-bb83402b-6594-4189-948b-fb9aaa048965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NzM4NTksIm5iZiI6MTcxNzY3MzU1OSwicGF0aCI6Ii81MjEzNDMxLzMzNzE4ODY2OC1iYjgzNDAyYi02NTk0LTQxODktOTQ4Yi1mYjlhYWEwNDg5NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTEzMjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzNjNTRhYzYzZGE4ZmU4OTUyMDU0YzAxOWUzMmYwNmUxMjFjZDYwYzVjNjUxMjI5NzU3NzdiMzQwN2VmZWVlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5dtk29rqdPpysy20UK43bKP3mOWAgZ6QZkdyoKugSUA)
> 
> 要启用这些可选参数

所以不能用我那种形式来做吗，选角界面的时候一般是单位还没生成。你这种事单位已经存在的情况

**Comment by tyhlovecm** [comment]
> ![image](https://private-user-images.githubusercontent.com/5213431/337188668-bb83402b-6594-4189-948b-fb9aaa048965.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjMzMjYsIm5iZiI6MTcxNzc2MzAyNiwicGF0aCI6Ii81MjEzNDMxLzMzNzE4ODY2OC1iYjgzNDAyYi02NTk0LTQxODktOTQ4Yi1mYjlhYWEwNDg5NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTIyMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTZkODJiMmRiYTI4NDU0M2ZmZWQ3NTE0ODZmYzZlMGI0YzIwOGQzMzM0ZDg0ZGQ0YTg2MzFhY2ZjNzk3MTA4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0WTnNATR5PweNMWyrgyTX7BCgERhO4PMB_QS05eB23c)
> 
> 要启用这些可选参数

这里没有对应的lua方法吗  没找到呢
