### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#393]
![image](https://github.com/y3-editor/y3-lualib/assets/65796389/4143d141-5e63-4ce4-8acf-d533c4b5b0ac)
woxi 请教个问题 我想使用这个函数如何转换为呢

**Comment by liang-1-qi** [comment]
我看参数都是需要 py对象

**Comment by liang-1-qi** [comment]
我想使用 --返回圆形范围内随机点
---@param point py.FVector3 # 圆心
---@param radius py.Fixed # 半径
---@return py.FVector3 # 随机点
function GameAPI.get_random_point_in_circular(point, radius) end
ECA是有个这个方法的，lua提供的api没有这个转换后的函数
![image](https://github.com/y3-editor/y3-lualib/assets/65796389/bdffd27a-3c4d-49ce-a6ed-f66695dba24c)

**Comment by padoruuu** [comment]
y3.point(0,0):get_point_offset_vector(math.random(360), 500)

**Comment by sumneko** [comment]
> ![image](https://private-user-images.githubusercontent.com/65796389/338024362-4143d141-5e63-4ce4-8acf-d533c4b5b0ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDA2NTAsIm5iZiI6MTcxODEwMDM1MCwicGF0aCI6Ii82NTc5NjM4OS8zMzgwMjQzNjItNDE0M2QxNDEtNWU2My00Y2U0LThhY2YtZDUzM2M0YjViMGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEwMDU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDNlNDg0ODU2YTI1Yzk2YTk5NDJjY2ZkNDI0MWFiNGEwMDZkY2ZkMmMyOGE4MjNhN2I3N2NiMTFjMzlhNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTnbuCN-afZpaWHSxvvtC0Xxq6lDHPWjmQuYpDVej30) woxi 请教个问题 我想使用这个函数如何转换为呢

对应的接口在 `y3.road` 里

**Comment by sumneko** [comment]
> y3.point(0,0):get_point_offset_vector(math.random(360), 500)

这个算法在平面上是不均匀的，靠近圆心的部分更加密集
