### ISSUE TITLE
今天更新了项目 之前正常运行的代码，爆错了，有关于运动器的

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#396]
[Error]: 'StraightMoverArgs' object cannot set attribute collision_type
error writing Python attribute/item: 'StraightMoverArgs' object cannot set attribute collision_type

**Comment by liang-1-qi** [comment]
是不是新版本的lua库，不兼容之前的

**Comment by liang-1-qi** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/65796389/059fd35b-2335-4640-a1b6-2ecbd1df2904)

**Comment by sumneko** [comment]
漏改了一处，稍等

**Comment by sumneko** [comment]
更新试一下

**Comment by liang-1-qi** [comment]
> 更新试一下

嗯嗯，可以了
