### ISSUE TITLE
关于区域注册事件的问题

### ISSUE THREAD

**Issue by Perlistan** [y3-editor/y3-lualib#397]
```lua
y3.game:event('游戏-初始化', function()
    local raidArea2 = {
        10020,
        10022,
    }

    for _, areaID in pairs(raidArea2) do
        y3.area.get_by_res_id(areaID):event("区域-进入", function(trg, data)
            print("进入了区域")
        end)
    end
end)
```

编辑器中有 N 个区域，我想选择 2 个区域注册事件，但运行游戏后日志会打印 N 次【进入了区域】而不是指定的 2 个

请问这是 BUG 还是使用不当

![QQ图片20240612021059](https://github.com/y3-editor/y3-lualib/assets/26273339/7d919606-cf46-4d37-ac7c-b16147c3f635)

**Comment by Perlistan** [comment]
补充：ECA - 任意单位进入指定区域

也会触发遍历所有区域的问题

![QQ图片20240612031050](https://github.com/y3-editor/y3-lualib/assets/26273339/eac72ce3-365e-43e8-85ee-92420569e600)
![QQ截图20240612031144](https://github.com/y3-editor/y3-lualib/assets/26273339/c192b295-da1b-4d67-b882-a02a310ef952)

**Comment by sumneko** [comment]
检查一下是不是你在进入区域事件里创建了单位或移动了单位
