### ISSUE TITLE
关于计时器的问题

### ISSUE THREAD

**Issue by Perlistan** [y3-editor/y3-lualib#398]
使用 ltimer 计时器并不准确，等待 3 秒会变成 4 秒、参数写越长实际等待的时间越长

**Comment by sumneko** [comment]
你是用什么对比时间的？

**Comment by sumneko** [comment]
我才知道这个逻辑帧是可以调的，我研究一下怎么获取你设置的值

**Comment by sumneko** [comment]
加个 `y3.config.logic_frame = 16`
