### ISSUE TITLE
一部分类似于get_table的api，不再像script/y3那样绑定在 y3 上，而是绑定在 y3.game上

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#4]
请问后续是遵循此标准进行开发调整现有代码，还是会考虑做兼容？
另外 const 全局变量也取消掉了

**Comment by sumneko** [comment]
以后都会绑在y3.game 上，如果你要兼容自己以前的代码，可以自己加一行 `const = y3.const`
