### ISSUE TITLE
技能相关

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#40]
事件里`data.ability_target_unit` 无法获取
```lua
y3.game:event("施法-完成", function(_, data)
    local target_unit = data.ability_target_unit
end)
```
调试器控制台输出: 
```log
data.ability_target_unit
:85: (EVAL):4: syntax error near 'end'
```

**Comment by xuhuanzy** [comment]
新问题, 无法获得施法方向, 运动器需要施法方向才能跟指示器方向一致.
`data.ability:get_angle(cast) ` 的参数 cast 哪里获取? 
`data.ability:get_ability_cast_direction(data)` 提示 `error reading Python attribute/item`

**Comment by xuhuanzy** [comment]
运动器里单位碰撞事件无法触发

```lua
local ammo = y3.projectile.create({
	key = 134243081,
	target = owner:get_point(),
	owner = owner,
	ability = ability,
	visible_rule = 1,
	time = -1,
	remove_immediately = true
})

ammo:mover_line({
	angle = 0,
	distance = 1000,
	speed = 1000,
	init_height = 50,
	hit_radius = 80,
	on_hit = function(mover, mover_target)
		print("on_hit")
	end,
})
```
on_hit 无法触发

**Comment by xuhuanzy** [comment]
断点下在调试控制台执行导致python报错的函数会导致事件链断掉.
```lua
y3.game:event("施法-出手", function(_, data)
	--- 在此断点
	函数1
end)

y3.game:event("施法-完成", function(_, data)
	--- 断点2
end)
```
在调试控制台输入 `data.ability:selected_location_by_ability(data)`, 函数与后续事件均不执行

**Comment by sumneko** [comment]
> 

![image](https://github.com/y3-editor/y3-lualib/assets/5213431/2cb06ddd-a370-49c5-a0fd-afe726546f53)

我测试是可以的，应该是 #41 导致的问题

**Comment by xuhuanzy** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/5213431/256761479-2cb06ddd-a370-49c5-a0fd-afe726546f53.png)
> 
> 我测试是可以的，应该是 #41 导致的问题

没注意更新评论去掉了，事件里data.ability_target_unit 无法获取是在 技能指示器 是非指向性的情况下出现的，把技能指向器设为箭头就会出现这个问题。暂时用判断指示器类型绕过了。

**Comment by sumneko** [comment]
> 没注意更新评论去掉了，事件里data.ability_target_unit 无法获取是在 技能指示器 是非指向性的情况下出现的，把技能指向器设为箭头就会出现这个问题。暂时用判断指示器类型绕过了。

这个情况下本来就不应该能取目标单位吧

**Comment by xuhuanzy** [comment]
> > 没注意更新评论去掉了，事件里data.ability_target_unit 无法获取是在 技能指示器 是非指向性的情况下出现的，把技能指向器设为箭头就会出现这个问题。暂时用判断指示器类型绕过了。
> 
> 这个情况下本来就不应该能取目标单位吧

不报错返回个nil就行, 
另外这种情况下要取目标方向跟目标地点, 但这两个api都用不了.
