### ISSUE TITLE
单位死亡的疑问

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#400]
for i = 1, 100 do
        local u = y3.unit.create_unit(y3.player(1), 134278237, y3.point(0,0), 0)
        u:event('单位-死亡',function (trg)

        end)
        u:kill_by(u)
    end

这段代码，在y3助手视图那边未回收是100
如果注释掉死亡事件，就可以正常回收了

**Comment by padoruuu** [comment]
还有个无法理解的。。上面的代码（不监听死亡事件的情况下）
在我项目内会一直保持引用，需要我手动执行collectgarbage("collect")才会回收，并且内存释放
我新建一个空地图，就会自动回收释放

测试环境就地形那些不同，用了相同的单位物编测试，并且代码只有一个y3库和main.lua做测试

**Comment by sumneko** [comment]
最终能回收就行

**Comment by padoruuu** [comment]
可是我测试的给单位加上死亡事件，就算调用collectgarbage("collect")也没回收

**Comment by sumneko** [comment]
好像是有问题，我晚点研究一下
