### ISSUE TITLE
y3.config.log.toGame 判断反了吧 log.debug 里还有一次正的判断 导致这个print_to_game 根本关不掉

### ISSUE THREAD

**Issue by Ermao-programmer** [y3-editor/y3-lualib#401]
--重载print

--等价于 `log.debug`。另外在开发模式中，还会确保打印到游戏窗口中。
---@param ... any
function print(...)
    local message = log.debug(...)
    if  y3.game.is_debug_mode()
    and not y3.config.log.toGame then
        print_to_game(message)
    end
end

**Comment by sumneko** [comment]
"还会确保打印到游戏窗口中"

**Comment by Ermao-programmer** [comment]
![screenshot-20240613-155806](https://github.com/y3-editor/y3-lualib/assets/7261991/cc121efe-84fb-4c3e-b9a5-eaa97c7a773e)
![screenshot-20240613-155816](https://github.com/y3-editor/y3-lualib/assets/7261991/47e2086c-8264-48f1-a4d5-cac692aca158)

**Comment by Ermao-programmer** [comment]
也就是在开发模式下怎么都会打印到游戏窗口是吧

**Comment by Ermao-programmer** [comment]
既然要设置y3.config.log.toGame = y3.game.is_debug_mode() 感觉118行 有点多余加呢
