### ISSUE TITLE
关于行为树的运行反馈问题

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#403]
1:定义了 New(Classname.Service)(0.5, function())后,这个意思是0.5秒执行一次吧?但是我看示例中还是用了计时器执行GameContext.Update(0.5)来刷新行为树,那么这个New(Classname.Service)(0.5, function())怎么理解呢?
2:行为树代码如果出错,控制台没有任何反馈,我只知道游戏异常了,这样很难发现问题出在哪里,希望能添加更多的错误提示.

**Comment by sumneko** [comment]
@xuhuanzy

**Comment by xuhuanzy** [comment]
1. 看原始的c#项目的文档，readme有链接，Update是更新行为树，Service是在更新时触发的，如果你不update那么Service就不会触发。
2. 异步问题应该自己管理，目前没时间处理这个，或许你试试最外层套一个y3.player.with_local？

**Comment by ApolloHY** [comment]
好的,我去查看原始文档
第二个问题是代码出错的问题,不是异步,比如代码导致的错误,VSCODE上没有提示,启动游戏后在控制台也没有任何错误提示.

**Comment by xuhuanzy** [comment]
> 好的,我去查看原始文档 第二个问题是代码出错的问题,不是异步,比如代码导致的错误,VSCODE上没有提示,启动游戏后在控制台也没有任何错误提示.

什么代码错误？

**Comment by ApolloHY** [comment]
就是代码写错啦

**Comment by ApolloHY** [comment]
行为树代码报错,在控制台没有报错提示.

**Comment by xuhuanzy** [comment]
哪里的？行为树错误我是直接error()的，不应该没有显示

**Comment by ApolloHY** [comment]
我现在改好了,之前不知道怎么弄的,或者直接删除一个括号,启动游戏,也没有报错提示
