### ISSUE TITLE
区域事件返回的触发器移除后, 无法在添加事件

### ISSUE THREAD

**Issue by ChNopx** [y3-editor/y3-lualib#405]
-- 随便在物编创建个多边形区域
local area =  y3.area.get_polygon_by_res_id(12312)

local tr = area:event('区域-进入', function(trg, data))
        print('进入区域')
end)

-- 这里移除过触发器, 会导致后续事件失效
tr:remove() 

local tr = area:event('区域-进入', function(trg, data))
        -- 这里已经失效了
        print('进入区域')  
end)

**Comment by sumneko** [comment]
测了一下已经修复了，虽然我不记得啥时候修的了。如果还有问题重开issue
