### ISSUE TITLE
main.lua调用了2次

### ISSUE THREAD

**Issue by Zui0** [y3-editor/y3-lualib#407]
【问题】
在文件main.lua中，使用print语言打印，发现实际情况被调用了2次，请问是什么原因？按理说main.lua应该只调用1次

【附加信息】
1、main.lua 代码
![image](https://github.com/y3-editor/y3-lualib/assets/11577481/a1f406eb-bde2-4578-a132-f8820ad9501d)

2、代码项目结构图
![image](https://github.com/y3-editor/y3-lualib/assets/11577481/f56ab134-d1f2-4fa5-b265-0372b764b6f1)

【运行结果】
![image](https://github.com/y3-editor/y3-lualib/assets/11577481/2b9e53e2-60cd-46ad-959e-364c494fd745)

**Comment by padoruuu** [comment]
是print输出了两次，我也一样
