### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#411]
--设置技能的建造目标类型(build_id)
---@param new_build_id py.UnitKey # 单位物编ID
function Ability:api_set_ability_build_id(new_build_id) end

--设置技能的限制建造区域
---@param area py.Area # 区域对象
function Ability:api_set_ability_build_area(area) end

这两个目前是还没有吗，大概几号会更新进来呢

**Comment by sumneko** [comment]
可能是27号，具体关注编辑器更新公告，ECA里有就能用
