### ISSUE TITLE
print没有在日志窗口输出

### ISSUE THREAD

**Issue by Zui0** [y3-editor/y3-lualib#413]
【问题】
print没有在日志窗口输出，但在游戏里面会有输出

【代码】
![image](https://github.com/y3-editor/y3-lualib/assets/11577481/478d70c9-f9b7-4a9e-b751-b03080a53a21)

【示例截图】
1、游戏中有输出
![image](https://github.com/y3-editor/y3-lualib/assets/11577481/976cbde0-d2ae-448e-b2f6-89192dc300b4)
2、日志窗口没有输出
![image](https://github.com/y3-editor/y3-lualib/assets/11577481/344b5509-57c3-4fe0-9f9f-46601b074618)

**Comment by Zui0** [comment]
同时如果把y3.config.log.toGame = false，还是会在游戏中输出，并不会屏蔽

**Comment by sumneko** [comment]
> 同时如果把y3.config.log.toGame = false，还是会在游戏中输出，并不会屏蔽

设定如此
