### ISSUE TITLE
单位移除

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#415]
技能按钮监听鼠标进入事件，然后获取当前选中的单位，如果存在选中的单位就获取他的某个技能
BUG：
当选中的单位被执行remove后鼠标进入技能按钮调用单位相关的API就报错了

目前我自己的解决方案：selecting_unit and not selecting_unit._removed_by_py，但是判断_removed_by_py好像不太合适

**Comment by sumneko** [comment]
987f414f424bffbbbd09b6c7968d44abdba58270  试试这个提交
