### ISSUE TITLE
能否增加一个获取 标签，目前只有添加和删除

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#416]

**Comment by padoruuu** [comment]
不是还有has_tag

**Comment by liang-1-qi** [comment]
> 不是还有has_tag

因为我想判断 两个物品的标签是否相等

**Comment by sumneko** [comment]
可以用 `y3.object` 库读物编

**Comment by liang-1-qi** [comment]
> 可以用 `y3.object` 库读物编

这个我知道 物品读取出来是个 userdata类型 还需要自己再处理一下，我的意思后面 能出个直接获取的方法吗

**Comment by sumneko** [comment]
> > 可以用 `y3.object` 库读物编
> 
> 这个我知道 物品读取出来是个 userdata类型 还需要自己再处理一下，我的意思后面 能出个直接获取的方法吗

那我用Lua封装一下
