### ISSUE TITLE
命令单位丢弃物品，有时候有效果有时候没效果

### ISSUE THREAD

**Issue by liang-1-qi** [y3-editor/y3-lualib#419]

**Comment by padoruuu** [comment]
攻击和放技能的时候就会这样，攻击频率高了 物品都捡不起来

**Comment by liang-1-qi** [comment]
> 攻击和放技能的时候就会这样，攻击频率高了 物品都捡不起来

我一直自动释放技能 频率特别快，但是还是能捡起来，就是丢弃的指令没效果，有时候有效果

**Comment by sumneko** [comment]
你是希望单位走过去把物品丢下来，还是只是希望物品掉下来？

**Comment by liang-1-qi** [comment]
> 你是希望单位走过去把物品丢下来，还是只是希望物品掉下来？

我希望装备直接掉在我传参的点

**Comment by sumneko** [comment]
用 `Item:drop`
