### ISSUE TITLE
反应BUG  获取不了触发器

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#426]
local u=y3.object.unit[134267382]
local trigger=u:event('单位-死亡',function (trg, data)
    print('111')
end)
print(trigger)
这里打印的trigger是nil

**Comment by kneesbuster** [comment]
trigger是挂在实例上的，给物编模板挂的trigger也是模板实例化之后转发给实例的
```
local u=y3.object.unit[134267382]
local trgMap134267382={}
local trigger=u:event('单位-死亡',function (trg, data)
    trgMap134267382[data.unit]=trg
end)
```
这样试试

**Comment by ApolloHY** [comment]
嗯哼,这样是可以的,但是每次怪物死亡的时候都会有一个trgMap134267382[data.unit]=trg,不太舒服..

**Comment by ApolloHY** [comment]
@kneesbuster 嗯哼,这样是可以的,但是每次怪物死亡的时候都会有一个trgMap134267382[data.unit]=trg,不太舒服..
