### ISSUE TITLE
镜头跟随无效

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#43]
`y3.camera.set_camera_follow_unit(y3.player(1), unit,  nil, nil, nil)`

eca正常

**Comment by 200774491** [comment]
你可以试试
local py_player = GameAPI.get_role_by_role_id(1)
local py_unit = GameAPI.get_unit_by_id(id)
GameAPI.camera_set_followmera_set_follow_unit(py_player ,py_unit ,0,0,0)

**Comment by 200774491** [comment]
你可以试试
local py_player = GameAPI.get_role_by_role_id(1)
local py_unit = GameAPI.get_unit_by_id(id)
GameAPI.camera_set_follow_unit(py_player ,py_unit ,0,0,0)

**Comment by xuhuanzy** [comment]
> 你可以试试 local py_player = GameAPI.get_role_by_role_id(1) local py_unit = GameAPI.get_unit_by_id(id) GameAPI.camera_set_follow_unit(py_player ,py_unit ,0,0,0)
以下有效: 
```lua
y3.camera.set_camera_follow_unit(y3.player(1), unit, 0, 0, 0)
```
被eca转lua里不需要后面三参数误导了
