### ISSUE TITLE
键盘按下无法触发

### ISSUE THREAD

**Issue by baiyuek** [y3-editor/y3-lualib#44]
`y3.game:event("游戏-初始化",function (trg, data)
    y3.game:event("键盘-按下",y3.const.KeyboardKey['Z'],function (trg, data)
        local p = data.player
        print 'z'
        y3.player.select_unit(p,y3.unit.get_by_res_id(6))
    end)
end)`

**Comment by sumneko** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/5213431/d6ef6fbe-fb6c-44c0-87f1-ad6238facb81)

我测试了一下可以正常工作

**Comment by baiyuek** [comment]
我这边也没问题了。
