### ISSUE TITLE
似乎无法准确的判断单位是否停止移动？

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#45]

**Comment by 200774491** [comment]
使用停止寻路事件
判断单位是否在移动的时候,如果移动的目标点是不可通行地面,且单位在不可通行的边缘,就会判断单位是在移动

**Comment by 200774491** [comment]
使用停止寻路事件
判断单位是否在移动的时候,如果移动的目标点是不可通行地面,且单位在不可通行的边缘,就会判断单位是在移动中.

**Comment by 200774491** [comment]
还有一个就是game.lua文件649行---获取运动器绑定投射物 
function M.get_mover_bound_projectiles() 这个方法似乎没有吧data写到参数里面 
原文:
---@return Projectile projectile 投射物 
---获取运动器绑定投射物 
function M.get_mover_bound_projectiles()
    local py_projectile = GameAPI.get_projectile_by_id(data['mover_owner_projectile'])
    return projectile.get_by_handle(py_projectile)
end

**Comment by sumneko** [comment]
用 `Unit:is_moving()`
