### ISSUE TITLE
UI的创建位置问题

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#46]
如果ui创建过程中不去设置ui的锚点（默认是xy是0.5锚点）此时拉伸窗口会导致UI向左偏移,
不去拉伸如果窗口化创建的UI位置 和全屏创建UI位置也会发生奇怪的偏移
如果在创建UI设置一下锚点为1,0(x,y),就不会发生偏移问题
假设：我现在都是这样处理了,未来那天我图发布了突然修复了这个问题？,所以想问下这个问题是否处理？

**Comment by 200774491** [comment]
eca的界面编辑器 和创建的UI都是这个问题

**Comment by 200774491** [comment]
另外UI相关api缺失太多例如设置字体api 目前修改字体只能通过eca的界面编辑器来改变

**Comment by 200774491** [comment]
另外UI相关api缺失太多例如设置字体api 目前修改字体只能通过eca的界面编辑器来改变,如果我创建的text就没办法修改字体

**Comment by sumneko** [comment]
编辑器、引擎本身的问题，如果你加了官方popo群的话可以提在群里。
如果没有的话我可以帮你提。

**Comment by 200774491** [comment]
你帮忙提吧具体原因不详,应该是和UI创建时候的锚点计算,和屏幕分辨率 方面相关

**Comment by sumneko** [comment]
> 不去拉伸如果窗口化创建的UI位置 和全屏创建UI位置也会发生奇怪的偏移

这句话看不懂

**Comment by 200774491** [comment]
就是如果你进入游戏时,是窗口化,和全屏(指编辑器内运行)

和你运行独立游戏的时候假设是全屏的 如果不使用编辑器的界面编辑器创建UI,直接创建UI就会发生偏移比如设置一个UI大小是50
位置是960,540 假设当时游戏分辨率是1920*1080(16:9)那么我UI锚点位置是0.5*0.5（0.5应该是代指中心锚点,UI创建默认是0.5）但是实际创建的位置如果,是编辑器独立游戏那么位置是中心点没问题但是窗口化时候他会发生偏移

**Comment by 200774491** [comment]
以为不太可能我地图制作的时候还要独立游戏运行(全屏)去创建UI那样太影响效率了

**Comment by 200774491** [comment]
因为不太可能我地图制作的时候还要独立游戏运行(全屏)去创建UI那样太影响效率了

**Comment by 200774491** [comment]
你在y3的656413818群内吗？如果在我给你录制一个视频发给你可能更加直观的看到不太好描述他具体问题我都有点迷总之找不到规律的诡异偏移

**Comment by sumneko** [comment]
不在，不过这个问题听起来是引擎的问题，我明天帮你转交给引擎组

**Comment by 200774491** [comment]
夕佬加个群吧,太多问题了

**Comment by sumneko** [comment]
> 夕佬加个群吧,太多问题了

Lua库的问题就在这里开issue问就好了，非Lua的问题你问我我也只能帮你转交一下

**Comment by 200774491** [comment]
好的,因为我没使用你这套,只是作为api参考,我是直接调用的GameAPI自己封装的一套框架
但是目前已经想摆烂了
