### ISSUE TITLE
GameAPI.api_physics_raycast(a2, a3)这个射线方法怎么用？

### ISSUE THREAD

**Issue by 314599782** [y3-editor/y3-lualib#463]
[error]'BlackBoxClient' object has no attribute 'core_3d'
error during Python call: 'BlackBoxClient' object has no attribute 'core_3d'
stack traceback:
        [C]: in field 'api_physics_raycast'

**Comment by sumneko** [comment]
ECA里没有对应的功能的话，就是已经废弃了
