### ISSUE TITLE
莫名的大内存申请

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#472]
哈喽，需要帮助。

监控发现哪怕是空项目，时不时会有2M甚至4M的内存被申请导致一个巨大的帧波动，除了这个之外，时不时(没找到规律)还有100K左右的内存申请导致哪怕一个空函数也会耗时巨大比如0.8ms

这是为什么，可能得原因是啥，我们能做什么呢？

PS. 为了拿到这些数据启用了network模块

**Comment by xiaoqiangCai** [comment]
内存申请与耗时之间的关系，从打点时间上吻合

**Comment by xiaoqiangCai** [comment]
大内存必然是2M或者4M这样的关系，小内存(上文100K)则不固定，可能80\90，可能150这样

**Comment by sumneko** [comment]
你说的内存指的是Lua使用 `collectgarbage 'count'` 获取的内存，还是整个进程占用的内存？

**Comment by sumneko** [comment]
![QQ_1721013921366](https://github.com/user-attachments/assets/08539c01-dc4b-4d8f-9f05-f92e0f7abbab)
我使用自己的测试项目，Lua虚拟机的内存占用始终没有超过7M

**Comment by xiaoqiangCai** [comment]
> 你说的内存指的是Lua使用 `collectgarbage 'count'` 获取的内存，还是整个进程占用的内存？

是的，统计值都是通过这个拿到的

**Comment by xiaoqiangCai** [comment]
> ![QQ_1721013921366](https://private-user-images.githubusercontent.com/5213431/348592678-08539c01-dc4b-4d8f-9f05-f92e0f7abbab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTQ1NDUsIm5iZiI6MTcyMTAxNDI0NSwicGF0aCI6Ii81MjEzNDMxLzM0ODU5MjY3OC0wODUzOWMwMS1kYzRiLTRkOGYtOWYwNS1mOTJlMGY3YWJiYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDMzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjdlNDcwYmI3YmIxMDM1Nzc0YWFmOTMyYjI0Zjg5ZWE5ZmRkMjUzZjVkYzM5NjcxMjNkM2ExMmYyMjM3N2MxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oAiinRD3uY4prpavyftZwYgC839M_pmwJFz-WfTuwzA) 我使用自己的测试项目，Lua虚拟机的内存占用始终没有超过7M

我的测试项目不太好发给你，你的这个能发给我不，我跑一下看看呢

**Comment by sumneko** [comment]
[Y3库开发3.zip](https://github.com/user-attachments/files/16229820/Y3.3.zip)

**Comment by xiaoqiangCai** [comment]
> [Y3库开发3.zip](https://github.com/user-attachments/files/16229820/Y3.3.zip)

好的

**Comment by xiaoqiangCai** [comment]
我把监控移入之后，纯粹只监控内存变化，跑了一段时间，刚开始是挺正常的，还是发现了大内存的申请，小内存不断。这个过程中，我把clock的移除了，纯粹只有count和network

![image](https://github.com/user-attachments/assets/957de4dd-c88d-4277-b2a3-9c120d3c9d94)

**Comment by sumneko** [comment]
这些坐标的单位是啥

**Comment by xiaoqiangCai** [comment]
[script.zip](https://github.com/user-attachments/files/16230672/script.zip)

**Comment by sumneko** [comment]
你的代码太复杂了，而且还引入了自己的dll，很难判断

**Comment by xiaoqiangCai** [comment]
> 你的代码太复杂了，而且还引入了自己的dll，很难判断

额，我给你的script里面，只用到了dll的clock内容。另外，整个逻辑就是在mentest里面每帧统计了一个count内存，然后上传，没了

**Comment by xiaoqiangCai** [comment]
> > 你的代码太复杂了，而且还引入了自己的dll，很难判断
> 
> 额，我给你的script里面，只用到了dll的clock内容。另外，整个逻辑就是在mentest里面每帧统计了一个count内存，然后上传，没了

甚至，案发现场，我是把clock的代码都注释掉了

**Comment by sumneko** [comment]
获取时间可以用 `os.clock_banned` 或 `python.debug_ns_timestamp`
结果可以先打印到日志里，然后解析一下日志

毕竟我这里空跑只有6M内存，而你的截图里都上90M了，很难不怀疑是你引入的dll有啥问题

**Comment by xiaoqiangCai** [comment]
> 获取时间可以用 `os.clock_banned` 或 `python.debug_ns_timestamp` 结果可以先打印到日志里，然后解析一下日志
> 
> 毕竟我这里空跑只有6M内存，而你的截图里都上90M了，很难不怀疑是你引入的dll有啥问题

启动的时候也是跟你一样的，个位数的内存，截图这是是给他跑了两小时之后的，我会看大内存警告找出来的

**Comment by xiaoqiangCai** [comment]
我把dll去掉吧，理论上说，我就是怕这个会对你判断有影响，案发的时候特地把y3.gclock相关的在memtest里面的代码注释掉才跑的。

我完全移除dll，再跑一轮看看

**Comment by xiaoqiangCai** [comment]
![image](https://github.com/user-attachments/assets/396d8901-2ead-4b23-929d-3d4fc051365e)

在4000帧的时候，就出现了一个67的小内存，这次是完全没有dll的

**Comment by sumneko** [comment]
理论上空跑无论跑多久内存都内存都不应该变化的，90+M应该有内存泄露了

**Comment by sumneko** [comment]
啥叫67的小内存

**Comment by xiaoqiangCai** [comment]
![image](https://github.com/user-attachments/assets/6a0dbbd9-1a7a-4c1d-86ee-45cadef0c24e)

就是比较前后两帧的内存变化，值太大了，我就输出来一个警告

**Comment by xiaoqiangCai** [comment]
这里单位是KB，跟我之前提到的小内存(100KB左右复合)

**Comment by xiaoqiangCai** [comment]
![image](https://github.com/user-attachments/assets/41cbd056-31b5-4286-9ddb-1ebcf659ee13)

这个经历几轮GC之后，内存的基点确实是在不停上涨，我不太懂为啥，是因为对象进入老年代，没有触发full gc的原因？

**Comment by sumneko** [comment]
做个按键事件手动调用一下 collectgarbage() 看看，如果能变回初始内存大小就不用管

**Comment by xiaoqiangCai** [comment]
降不下去，手动的，基点也是在缓慢增长

**Comment by sumneko** [comment]
![QQ_1721027371937](https://github.com/user-attachments/assets/d307c086-c7d4-4e19-840b-277299123a10)
我这边快进到13个小时依然只有6M内存占用，应该是你代码里有内存泄露

**Comment by sumneko** [comment]
你用 `.ss` 打印一下内存快照看看，然后用 `.ct` 查询一下可疑对象的应用

**Comment by xiaoqiangCai** [comment]
> ![QQ_1721027371937](https://private-user-images.githubusercontent.com/5213431/348623078-d307c086-c7d4-4e19-840b-277299123a10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjc3MDcsIm5iZiI6MTcyMTAyNzQwNywicGF0aCI6Ii81MjEzNDMxLzM0ODYyMzA3OC1kMzA3YzA4Ni1jN2Q0LTRlMTktODQwYi0yNzcyOTkxMjNhMTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMDcxMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjY3NjgwYzY3YWE4NjEzMjQwY2UyNjgxYjEwOWM0Mzk5NjE5ZTRiODUwMzIyNDg0ZmY1MGNjYmIwOTFmODU1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.leUYcLeFu_k0vd7G9YC1oPtLlryEtmMyKAhZFZRCe54) 我这边快进到13个小时依然只有6M内存占用，应该是你代码里有内存泄露

1. 咋快进的...还有这功能？
2. 我看代码是比较不出来了，我试试你说的这个内存快照的方法

**Comment by xiaoqiangCai** [comment]
我好像找到了，我改一下试一下看看。这个snapshot工具很6

**Comment by xiaoqiangCai** [comment]
> 你用 `.ss` 打印一下内存快照看看，然后用 `.ct` 查询一下可疑对象的应用

基点涨的是修复了，但是上面的提到的小内存问题，还是会有

**Comment by sumneko** [comment]
内存持续增长很正常，计时器底层和network都会不停的制造内存。一帧增长100k有可能是你序列化、反序列化了一个比较大的数据结构。

**Comment by xiaoqiangCai** [comment]
> 内存持续增长很正常，计时器底层和network都会不停的制造内存。一帧增长100k有可能是你序列化、反序列化了一个比较大的数据结构。

不是这个意思，我抓一个给你看一下，他的增长时间点很多时候对应的是空函数的返回，就很奇怪

**Comment by xiaoqiangCai** [comment]
好像抓不到了我认为有问题的小内存申请，目前出现的都基本是你说的那种情况，大部分应该是buff字符串拼接和序列化的消耗

**Comment by xiaoqiangCai** [comment]
还是会有这种情况的内存块申请，不知道为啥

![image](https://github.com/user-attachments/assets/a7834c03-1e65-43b6-b6ca-e49890d2eb08)

![image](https://github.com/user-attachments/assets/c5978cb2-ff4d-487f-afad-eda2cd644b6c)

delta=after-before, 问题是这段之间基本没逻辑，却显示开销了129KB...

**Comment by sumneko** [comment]
有没有触发 `log.error` ？

**Comment by xiaoqiangCai** [comment]
> 有没有触发 `log.error` ？

没有，前后日志在这了

![image](https://github.com/user-attachments/assets/f393feb3-376e-4df8-b6b7-03e1570a08f9)

**Comment by sumneko** [comment]
我之前看你代码好像网络会不定时回包？是不是刚好回了个包过来解析了一下

**Comment by xiaoqiangCai** [comment]
> 我之前看你代码好像网络会不定时回包？是不是刚好回了个包过来解析了一下

即使会这样，但是也说不通，因为在这个日志逻辑帧循序执行的吧，难到还会并行插入数据，或者说网络包底层会并行往lua写入数据吗

**Comment by sumneko** [comment]
简单看了下你的atex里面有几个数组会不停的扩展，他们预期会有多长？

**Comment by xiaoqiangCai** [comment]
> 简单看了下你的atex里面有几个数组会不停的扩展，他们预期会有多长？

一个trace日志的行数，在这里固定9或者10行

**Comment by xiaoqiangCai** [comment]
> > 简单看了下你的atex里面有几个数组会不停的扩展，他们预期会有多长？
> 
> 一个trace日志的行数，在这里固定9或者10行

![image](https://github.com/user-attachments/assets/849ac7b3-f7ac-4599-b5f9-02977d3ad1f4)

**Comment by sumneko** [comment]
之前测试的时候是关掉调试器的吗，我看你发我的代码里是注掉调试器的

**Comment by xiaoqiangCai** [comment]
> 之前测试的时候是关掉调试器的吗，我看你发我的代码里是注掉调试器的

没，我把那个调试器的代码挪到了main下了

上面事发的是开着调试器的

**Comment by sumneko** [comment]
关一下调试器试试看，调试器即使你不连接也会有一定开销的（会hook函数调用）

**Comment by xiaoqiangCai** [comment]
> 关一下调试器试试看，调试器即使你不连接也会有一定开销的（会hook函数调用）

我试一下，还得观察一下数据

**Comment by xuhuanzy** [comment]
> 你的代码太复杂了，而且还引入了自己的dll，很难判断

不是在平台下不能用dll吗

**Comment by xiaoqiangCai** [comment]
> > 你的代码太复杂了，而且还引入了自己的dll，很难判断
> 
> 不是在平台下不能用dll吗

本地环境下的

**Comment by xuhuanzy** [comment]
内存诊断工具用的啥

**Comment by xiaoqiangCai** [comment]
@sumneko 这个地方是问题吗

```lua
function json.encode(v)
    statusVisited = {}
    statusBuilder = {}
    encode(v)
    return table_concat(statusBuilder)
end
```
statusBuilder 需要在下一次调用encode时候才会释放，这样会不会导致对象容易晋升到老年代

**Comment by xiaoqiangCai** [comment]
> 内存诊断工具用的啥

自个写...

**Comment by xiaoqiangCai** [comment]
> 内存诊断工具用的啥

https://github.com/citizenfx/lmprof  这或许可以，但是还是需要二次修改后才能用的

**Comment by xiaoqiangCai** [comment]
@sumneko 

大内存申请2m/4m的地方居然是这一行，为什么....

```lua

function M:atex(desc, i)
    local a = self.now()   ---这已经替换成那个python的了
    local key = string.sub(string.reverse('' .. a), 3, 7)    ----  这里 sub 和 reverse 都是大内存产生的地方 有时候是sub有时候是reverse

... ...
```
![image](https://github.com/user-attachments/assets/762555d2-ceda-403d-98a1-ceee8f972449)
![image](https://github.com/user-attachments/assets/9ebb70f4-49ed-4a80-a9fa-68e593e15812)

这...

**Comment by xiaoqiangCai** [comment]
> @sumneko
> 
> 大内存申请2m/4m的地方居然是这一行，为什么....
> 
> ```lua
> function M:atex(desc, i)
>     local a = self.now()   ---这已经替换成那个python的了
>     local key = string.sub(string.reverse('' .. a), 3, 7)    ----  这里 sub 和 reverse 都是大内存产生的地方 有时候是sub有时候是reverse
> 
> ... ...
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7403230/350663263-762555d2-ceda-403d-98a1-ceee8f972449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjMxODEsIm5iZiI6MTcyMTQ2Mjg4MSwicGF0aCI6Ii83NDAzMjMwLzM1MDY2MzI2My03NjI1NTVkMi1jZWRhLTQwM2QtOThhMS1jZWVlOGY5NzI0NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMDgwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U2OTU3MzQ1OWM5OWUzOTQzN2ExOTNmZWMyNjIxNDVmZWE4ZWJkNDk3Yjc2YWY2NmMwODI4YWRiZTc4ZDRkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D3Hmq0OGIo6b-UuES07HxSOMwMiLm9OVvF5X9j_lVF4) ![image](https://private-user-images.githubusercontent.com/7403230/350663275-9ebb70f4-49ed-4a80-a9fa-68e593e15812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjMxODEsIm5iZiI6MTcyMTQ2Mjg4MSwicGF0aCI6Ii83NDAzMjMwLzM1MDY2MzI3NS05ZWJiNzBmNC00OWVkLTRhODAtYTlmYS02OGU1OTNlMTU4MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMDgwODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI3OGM1MDc3MDlmZTA1Yjk1Y2M2YWE2NTg0MTRmNjRmNTRhNTRjYzJlODEzYWY1OTg2NDI1MzI5MzJhMDI3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._GQl63eBZOpj0IYyZz8hBUHi4wHlyY_VlcdoMKnrCrA)
> 
> 这...

很多地方，在拼接字符串的时候，都会随机出现，感觉有点类似这个bug:  https://www.lua.org/bugs.html#5.4.6-6

**Comment by xiaoqiangCai** [comment]
> @sumneko
> 
> 大内存申请2m/4m的地方居然是这一行，为什么....
> 
> ```lua
> function M:atex(desc, i)
>     local a = self.now()   ---这已经替换成那个python的了
>     local key = string.sub(string.reverse('' .. a), 3, 7)    ----  这里 sub 和 reverse 都是大内存产生的地方 有时候是sub有时候是reverse
> 
> ... ...
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/7403230/350663263-762555d2-ceda-403d-98a1-ceee8f972449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzA5MzYsIm5iZiI6MTcyMTQ3MDYzNiwicGF0aCI6Ii83NDAzMjMwLzM1MDY2MzI2My03NjI1NTVkMi1jZWRhLTQwM2QtOThhMS1jZWVlOGY5NzI0NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTAxNzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTFjZDQ2ODEwZWRiMTkyZGEzNTQ5M2YwZDFjMDEyYTliYTFjMTJmNGViMzhlZDRlYzBmYzg5YjYwMTY5MzY4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BEEuU-1z4AaJU61iD5PTW85NwR4A4b8wcIdI2OHIit0) ![image](https://private-user-images.githubusercontent.com/7403230/350663275-9ebb70f4-49ed-4a80-a9fa-68e593e15812.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NzA5MzYsIm5iZiI6MTcyMTQ3MDYzNiwicGF0aCI6Ii83NDAzMjMwLzM1MDY2MzI3NS05ZWJiNzBmNC00OWVkLTRhODAtYTlmYS02OGU1OTNlMTU4MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTAxNzE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmFhNGQ3MmM2MTIyZGIzYTc0MDdlYTZmMTgyNWMxYmI2MzRjYWRkM2JkZDVhNDhiYTdkOWIxZGE3N2JlZTVlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XN-OM8iauDoQvEPnCNdsegpzSLBwZrYYkCI7JqQ6cdM)
> 
> 这...

基本上确定了，是lua的创建短字符串的时候，默认为短字符串构建一个hash值并存入一张全局hash表，是这个表扩容导致的大内存块申请。

短时间内创建大量的短字符串就会触发这个问题。

![image](https://github.com/user-attachments/assets/f3b86902-fa4b-4826-a60c-31f6e8918349)
