### ISSUE TITLE
显示unit:exchange_item接口已经被废弃了,有没有替代方法呢?

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#486]
毕竟这个接口要比shift_item方便很多

**Comment by sumneko** [comment]
是为了实现交换物品吗？

**Comment by ApolloHY** [comment]
是的哈

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月22日 17:41 |
| 收件人 | y3-editor/y3-lualib ***@***.***> |
| 抄送人 | ApolloHY ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [y3-editor/y3-lualib] 显示unit:exchange_item接口已经被废弃了,有没有替代方法呢? (Issue #486) |

是为了实现交换物品吗？

**Comment by ApolloHY** [comment]
@sumneko 是的哈,就是交换物品

**Comment by sumneko** [comment]
那就继续用，把废弃标志去掉了
