### ISSUE TITLE
能否增加创建地形预设加载完成的事件

### ISSUE THREAD

**Issue by oyjey123** [y3-editor/y3-lualib#489]
如题，以及封装下创建地形预设的接口，GameAPI.load_sub_scene

**Comment by xiaoqiangCai** [comment]
感觉，还不如开放动态创建装饰物功能，想咋搞咋搞

**Comment by oyjey123** [comment]
> 感觉，还不如开放动态创建装饰物功能，想咋搞咋搞

本来物编里面就有装饰物可以创建啊，只是你直接拖到场景的装饰物你是获取不到实例的。 你如果是想代码动态创建任意装饰物是不可能的，只能创建你已经声明过的装饰物

**Comment by xiaoqiangCai** [comment]
没啥不可能的，就是他们做不做。既然都有动态创建场景了，动态装饰物应该是他们下属功能或者类似的极简摆件，开不开放而已

**Comment by oyjey123** [comment]
> 没啥不可能的，就是他们做不做。既然都有动态创建场景了，动态装饰物应该是他们下属功能或者类似的极简摆件，开不开放而已

你玩家要下载资源的啊，你不提前声明装饰物，怎么计算你包体大小？不可能让玩家边玩边下吧？又不是传奇能搞微端
