### ISSUE TITLE
转移物品api不生效

### ISSUE THREAD

**Issue by yangxy6855** [y3-editor/y3-lualib#494]
![image](https://github.com/user-attachments/assets/a569e967-11e5-4acf-9923-7a2cbf1a0ad7)
转移物品的api 试了下没有生效，eca的是可以的

报错如下：（看源码好像是 物品-离开物品栏 的时候报的错）
![image](https://github.com/user-attachments/assets/7b1e338e-7b9d-4a5c-9a62-71b5f09d5db5)

**Comment by freewhel** [comment]
`hero:shift_item(aa, '背包栏', 1, true)`
用这个试试

**Comment by yangxy6855** [comment]
> `hero:shift_item(aa, '背包栏', 1, true)` 用这个试试
这个可以，感谢大佬~~~
