### ISSUE TITLE
UI get_child问题

### ISSUE THREAD

**Issue by ldoubil** [y3-editor/y3-lualib#498]
如所述 https://github.com/y3-editor/y3-lualib/commit/a229ec1cd1f299fb94514f5578e36d4129637f20#r146492923

**Comment by sumneko** [comment]
我测试下来UI只要是同步删的，所有玩家的判断结果都是一致的。
至于判空问题，是因为ECA那边忽略了空错误并继续往下执行，Lua则会抛出异常。事实上Lua这边 `get_child` 的返回值签名一直都是 `UI?`，就应该需要判空。

**Comment by sumneko** [comment]
不过测试了一下，ECA那边确实删除了控件后还是能获取出来，那还是和ECA保持一致吧

**Comment by ldoubil** [comment]
确实是直接返回nil比较好，但是之前写的东西太多了，
 如果全部都加上if 判空 会增加很多代码，毕竟之前有些直接get_child  就设置内容就可以。
判空通常只用于元件创建完成判断一次，子内容就不判断了。
现在需要临时存在变量判断完再使用。
其实如果一开始就遵守这个也很不错，现在确实有点比较难改

**Comment by ldoubil** [comment]
或许可不可以吧GameAPI.ui_comp_is_exist(py_ui) 变成配置项 ，默认还是现在这样但是允许关闭检测

**Comment by sumneko** [comment]
> 或许可不可以吧GameAPI.ui_comp_is_exist(py_ui) 变成配置项 ，默认还是现在这样但是允许关闭检测



> 或许可不可以吧GameAPI.ui_comp_is_exist(py_ui) 变成配置项 ，默认还是现在这样但是允许关闭检测



> 或许可不可以吧GameAPI.ui_comp_is_exist(py_ui) 变成配置项 ，默认还是现在这样但是允许关闭检测



> 或许可不可以吧GameAPI.ui_comp_is_exist(py_ui) 变成配置项 ，默认还是现在这样但是允许关闭检测

可以，我明天加个设置

**Comment by ldoubil** [comment]
> > 或许可不可以吧GameAPI.ui_comp_is_exist（py_ui） 变成配置项 ，默认还是现在这样但是允许关闭检测
> 
> > 或许可不可以吧GameAPI.ui_comp_is_exist（py_ui） 变成配置项 ，默认还是现在这样但是允许关闭检测
> 
> > 或许可不可以吧GameAPI.ui_comp_is_exist（py_ui） 变成配置项 ，默认还是现在这样但是允许关闭检测
> 
> > 或许可不可以吧GameAPI.ui_comp_is_exist（py_ui） 变成配置项 ，默认还是现在这样但是允许关闭检测
> 
> 可以，我明天加个设置

加了嘛😭

**Comment by sumneko** [comment]
忘了，我现在加一下

**Comment by sumneko** [comment]
加了
