### ISSUE TITLE
单位-击杀 事件触发时机错误

### ISSUE THREAD

**Issue by jiyao1990** [y3-editor/y3-lualib#499]
我这边"单位-击杀"事件是单位自己死亡以后触发的，是和"单位-死亡"一起触发的。

测试了编辑器内是正常的，使用不同单位注册"单位-击杀"，都是自己死亡以后触发。

打了log，source_unit和target_unit都是对的，只是触发的是target_unit

**Comment by sumneko** [comment]
我这边复现不出来，请提供一下演示代码

**Comment by jiyao1990** [comment]
新建一个空项目，地图放进去预设的关羽和刘备，刘备设置为中立敌对。
local M = y3.object.unit[134274912] --关羽

M:event("单位-击杀", function (trg, data)
    log.debug("关羽：" .. tostring(data.source_unit) .. "击杀了" .. tostring(data.target_unit))
end)

local X = y3.object.unit[134241735] --刘备

X:event("单位-击杀", function (trg, data)
    log.debug("刘备：" .. tostring(data.source_unit) .. "击杀了" .. tostring(data.target_unit))
end)

加载这个运行以后，关羽击杀刘备，log会显示：[2024-09-19-21-53-55] : [ Info]: 刘备：{unit|关 羽|1}击杀了{unit|刘 备|2}

**Comment by sumneko** [comment]
已修复
