### ISSUE TITLE
get_unit_in_area_by_camp

### ISSUE THREAD

**Issue by xiaoyaod** [y3-editor/y3-lualib#503]
get_unit_in_area_by_camp 可以传入什么样的参数

**Comment by xiaoyaod** [comment]
M:event("施法-出手",function (trg,data)
    local unit  = data.unit
    local area = y3.area.create_circle_area(unit:get_point(),800)
    local units =   area:get_unit_in_area_by_camp( y3.game.str_to_camp('中立敌对'))
    for i,value in ipairs(units) do
        local dummy =  y3.projectile.create{  key    = 134281805,
            owner =unit,
            target = unit:get_point()
            }
            dummy:mover_target {
               target_distance = 0,
                speed = 1001,
                target = value,
                height = 80,
                absolute_height=true,
 
                on_finish = function ()
                    unit:damage{
                        target = value,
                        type= '物理',
                        damage=unit:get_attr_base("物理攻击"),
                        }
                    dummy:remove()
                end
            }

    end 
end)


[2024-10-04-23-12-59] : [Error]: 字符串格式错误
error during Python call: 字符串格式错误
stack traceback:
	[C]: in field 'str_to_camp'
	.../maps/TD_template_new/script/y3\game\game.lua:214: in function 'y3.game.game.str_to_camp'
	.../ProjectName001/maps/TD_template_new/script/test.lua:19: in function <.../ProjectName001/maps/TD_template_new/script/test.lua:16>
	[C]: in function 'xpcall'
	.../maps/TD_template_new/script/y3\util\trigger.lua:168: in function 'y3.util.trigger.execute'
	.../maps/TD_template_new/script/y3\util\event.lua:166: in method 'notify'
	.../maps/TD_template_new/script/y3\util\event_manager.lua:153: in method 'notify'
	.../maps/TD_template_new/script/y3\util\object.lua:35: in function <.../maps/TD_template_new/script/y3\util\object.lua:27>
	[C]: in function 'xpcall'
	.../maps/TD_template_new/script/y3\util\trigger.lua:168: in function 'y3.util.trigger.execute'
	.../maps/TD_template_new/script/y3\util\event.lua:185: in method 'dispatch'
	.../maps/TD_template_new/script/y3\util\event_manager.lua:168: in method 'dispatch'
	.../maps/TD_template_new/script/y3\game\game_event.lua:57: in function 'y3.game.game_event.event_notify'
	.../TD_template_new/script/y3\game\py_event_subscribe.lua:280: in function <.../TD_template_new/script/y3\game\py_event_subscribe.lua:278>

**Comment by sumneko** [comment]
用 `y3.game.get_camp_by_id`
