### ISSUE TITLE
事件 技能-建造技能释放前  会报错

### ISSUE THREAD

**Issue by ApolloHY** [y3-editor/y3-lualib#504]
事件 技能-建造技能释放前  会报错

**Comment by sumneko** [comment]
具体是什么报错？来个截图

**Comment by ApolloHY** [comment]
object_event.lua:120: attempt to index a nil value (local 'master')
stack traceback:
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: in upvalue 'get_master'
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:135: in function 'y3.game.object_event.event_notify'
        .../maps/EntryMap/script/y3\game\py_event_subscribe.lua:281: in function <.../maps/EntryMap/script/y3\game\py_event_subscribe.lua:278> to gbk failed, e=not expecting type '<class 'LPMix.LuaError'>'
decode .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: attempt to index a nil value (local 'master')
stack traceback:
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: in upvalue 'get_master'
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:135: in function 'y3.game.object_event.event_notify'
        .../maps/EntryMap/script/y3\game\py_event_subscribe.lua:281: in function <.../maps/EntryMap/script/y3\game\py_event_subscribe.lua:278> to utf-8 failed, e=not expecting type '<class 'LPMix.LuaError'>'
encode .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: attempt to index a nil value (local 'master')
stack traceback:
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: in upvalue 'get_master'
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:135: in function 'y3.game.object_event.event_notify'
        .../maps/EntryMap/script/y3\game\py_event_subscribe.lua:281: in function <.../maps/EntryMap/script/y3\game\py_event_subscribe.lua:278> to gbk failed, e=not expecting type '<class 'LPMix.LuaError'>'
encode .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: attempt to index a nil value (local 'master')
stack traceback:
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:120: in upvalue 'get_master'
        .../felling/maps/EntryMap/script/y3\game\object_event.lua:135: in function 'y3.game.object_event.event_notify'
        .../maps/EntryMap/script/y3\game\py_event_subscribe.lua:281: in function <.../maps/EntryMap/script/y3\game\py_event_subscribe.lua:278> to utf-8 failed, e=not expecting type '<class 'LPMix.LuaError'>'
        好像是编码问题。

**Comment by sumneko** [comment]
最近大改过事件系统，更新看看？

**Comment by ApolloHY** [comment]
已解决
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月11日 17:38 |
| 收件人 | y3-editor/y3-lualib ***@***.***> |
| 抄送人 | ApolloHY ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [y3-editor/y3-lualib] 事件 技能-建造技能释放前 会报错 (Issue #504) |

最近大改过事件系统，更新看看？

**Comment by ApolloHY** [comment]
@sumneko 另外再求助一下,投射物创建的时候可以设置单位的挂接点,但是如果使用对象池的话,没有办法重新为投射物设置挂接点了,只能设置point,可以提供这类办法吗?

**Comment by sumneko** [comment]
> @sumneko 另外再求助一下,投射物创建的时候可以设置单位的挂接点,但是如果使用对象池的话,没有办法重新为投射物设置挂接点了,只能设置point,可以提供这类办法吗?

用编辑器自带的投射物池功能，在物编里有个选项启用

**Comment by ApolloHY** [comment]
我尝试过那个.好像并没有效果
