### ISSUE TITLE
增加从table 随机选择n个元素

### ISSUE THREAD

**Issue by xiaoyaod** [y3-editor/y3-lualib#512]
如果你想提的是编辑器或引擎本身的需求，请移步至 [论坛](https://create-bbs.reckfeng.com/forum.php?mod=forumdisplay&fid=25) 或者加QQ群：656413818

**Comment by xiaoyaod** [comment]
area  增加环形区域

**Comment by sumneko** [comment]
可以自己根据需求用 `y3.util.randomSortTable` `y3.util.map` `y3.util.valuesOf` 组合一下
