### ISSUE TITLE
Delete LinkedTable 会报错

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#516]
script/y3\tools\class.lua:218: can not delete undeclared class

**Comment by sumneko** [comment]
怎么还用了delete，这个类也没有 `__del` 方法，delete本来就没有用鸭

**Comment by xiazhixi** [comment]
为了做 IsValid 判断是否清除的，不行的话我们改下

**Comment by xiazhixi** [comment]
另外我们自定义的类也遇到了 Delete 报错的情况，我确认下。
