### ISSUE TITLE
GCHost 的 bindGC，能否在对象被 Delete 后调用是，自动 Delete 传入的对象

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#517]
有些情况下，当对象已经被 Delete 后，再次调用 bindGC，会导致传入的实例再也不会触发 Delete

**Comment by sumneko** [comment]
设计里 GCHost 被 remove 调以后传进去的对象就是会立即触发 Delete 的。来个演示代码？

**Comment by xiazhixi** [comment]
---@class ABuff
local ABuff = Class 'ABuff'

---@class ABuff: GCHost
Extends('ABuff', 'GCHost')

function ABuff:__init(unit)
    local u --[[@type Unit]] = unit
    self:bindGC(y3.timer.loop(0.5, function()
        if not IsValid(u) then
            print('单位id', u:get_id())
        end
    end))
    u:event('单位-死亡', function()
        Delete(self)
    end)
end

---@class Unit
local M = y3.unit
function M:append_buff()
    self:event('单位-死亡', function()
        New 'ABuff' (self)
    end)
end

y3.game:event('游戏-初始化', function(trg, ...)
    local target = y3.unit.get_by_id(1)
    local p = y3.point(500, 0)

    if target then
        target:add_state('禁止移动')
        target:add_state('无敌')
    end

    y3.timer.loop(0.1, function()
        local u --[[@type Unit]] = y3.unit.create_unit(y3.player.get_by_id(2), 201339863, p, -90)
        u:append_buff()
        if target then
            u:move_to_pos(target:get_point(), 0)
        end
    end)
end)

**Comment by xiazhixi** [comment]
> 设计里 GCHost 被 remove 调以后传进去的对象就是会立即触发 Delete 的。来个演示代码？

可以，请稍等，我再看下

**Comment by sumneko** [comment]
`append_buff` 的实现里，为什么是在死亡事件里才 `New 'ABuff' (self)` ？这是预期的吗？

**Comment by xiazhixi** [comment]
> `append_buff` 的实现里，为什么是在死亡事件里才 `New 'ABuff' (self)` ？这是预期的吗？

是为了模拟我描述的场景

**Comment by xiazhixi** [comment]
> `append_buff` 的实现里，为什么是在死亡事件里才 `New 'ABuff' (self)` ？这是预期的吗？

我描述的场景是 Extends 了 GCHost 的容器对象，如果已经被 Delete，再 bindGC 传入想绑定生命周期的实例，就会有问题。
我看到 GC:add 只是判断了传入对象是否 IsValid

**Comment by xiazhixi** [comment]
不知道能否如此修改：
```lua
function GCHost:bindGC(obj)
    if not self._gccontainer then
        ---@private
        self._gccontainer = New 'GC' ()
    end
    if type(obj) == 'function' then
        obj = New 'GCNode' (obj)
    end

    if not IsValid(self) then
        Delete(obj)
        return nil
    end

    return self._gccontainer:add(obj)
end
```
