### ISSUE TITLE
获取玩家鼠标位置返回值为0

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#52]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/8922a610-5e92-4b6a-8d65-ed2c85b5b145)
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/882fe19a-109e-4492-856b-4a458a24f645)
我又尝试并检查了代码发现还是获取不到？

**Comment by 200774491** [comment]
另外
GameAPI.set_ui_comp_follow_mouse(self:owner():handle(),self:handle(), is_follow)
并未生效似乎? 我在编辑器使用跟随鼠标这个func，控件会跑到左下角并且失效


--控制控件跟随鼠标
---@param role py.Role # 玩家
---@param comp_name string # 控件uid
---@param is_follow string # 事件名
function GameAPI.set_ui_comp_follow_mouse(role, comp_name, is_follow) end

**Comment by ldoubil** [comment]
### 可以尝试一下这个,或许遇到的是同样bug
#51

**Comment by sumneko** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/5213431/9f759271-648f-4fbc-9681-cc65951c875c)

我测试是正常的，看你截图你调用的API不对
