### ISSUE TITLE
[提问] Network允许在平台环境下链接外网吗？

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#522]
自己的服务器

**Comment by sumneko** [comment]
允许

**Comment by xuhuanzy** [comment]
话说lua环境能否默认加载protobuf.dll？实现了个纯lua的性能只有dll的12%左右。
不行的话我把纯lua的合并进第三方库？

**Comment by sumneko** [comment]
有内置的 `require 'pb' .loadCustomProtocol()` 会加载工程里的 `<地图>\custom\protocol\protocol.pb` 。目前只能固定读取这个位置，之后打算改成可以直接传个字符串

**Comment by xuhuanzy** [comment]
require 'pb'用法跟lua-probuf一致是吧？还是说是云风的那个？

**Comment by sumneko** [comment]
这部分不是我写的，自己调一下吧，返回一个表

**Comment by xuhuanzy** [comment]
应该是`lua-probuf`, 那玩意有个小bug, `int64`默认值被截断成了`int32`, 而且默认编译命令提供的dll的性能比用`Clion`一键优化编译出来的差10%左右.

**Comment by sumneko** [comment]
不懂，我都是用json的

**Comment by xuhuanzy** [comment]
话说, 语言服务器为什么使用你发布的插件版本, 会出现
````
-- 提示错误
local x = EditorAttrKey["法力值1544847"]
-- 无法提示错误, 但在项目只有单个文件的模拟测试中提示错误
owner:event("单位-属性变化", EditorAttrKey["法力值1544847"], function(trg, data)
```

但用自己fork下来的版本, 然后指定用于服务器exe路径就能两个都报错?

**Comment by sumneko** [comment]
单独开个issue，描述详细点
