### ISSUE TITLE
断线重连时 会回档是为什么 都是实时性的存档 编辑器版本是2最高的版本

### ISSUE THREAD

**Issue by Ermao-programmer** [y3-editor/y3-lualib#525]
或者可能玩家不正常退出的话 存档永远都不更新到服务端

**Comment by sumneko** [comment]
看不懂...描述的再详细一点

**Comment by Ermao-programmer** [comment]
我调用了个y3.save_data.save_boolean这个接口 用户强制断网或者闪退后触发断线重连 回来后 这个数值被回档了

**Comment by sumneko** [comment]
> 回来后 这些数值被回到了他们刚开局的状态

这个时间点是重新追帧到调用了 `save_xxx` 之后吗？

**Comment by Ermao-programmer** [comment]
追帧肯定追到断线的时候吧，要不他也看不到界面，save的调用逻辑都是在add_local_event里触发的

**Comment by Ermao-programmer** [comment]
方便qq语音下么

**Comment by sumneko** [comment]
> 方便qq语音下么

可以，有我QQ号吗

**Comment by Ermao-programmer** [comment]
有 我打了哈

**Comment by sumneko** [comment]
> 额 没接听

QQ发个消息
