### ISSUE TITLE
point

### ISSUE THREAD

**Issue by summmmmmmmn** [y3-editor/y3-lualib#534]
很久没更新框架，更新后发现y3.point返回的是userdata了，导致调用任何point类的Api都报错

**Comment by summmmmmmmn** [comment]
主要还导致自己添加的一些方法也没办法调用了

**Comment by xiazhixi** [comment]
遇到了相同的问题

**Comment by sumneko** [comment]
> 主要还导致自己添加的一些方法也没办法调用了

我看看兼容一下

**Comment by sumneko** [comment]
> 很久没更新框架，更新后发现y3.point返回的是userdata了，导致调用任何point类的Api都报错

具体哪个API，来个例子

**Comment by xiazhixi** [comment]
![_20241115142522](https://github.com/user-attachments/assets/c4bdf689-275b-4a2b-8532-44c87fd9a722)
所有的 get_point 都报错。
因为y3.point.create的 point 是个 Fixed32Vector

**Comment by sumneko** [comment]
更新一下试试
