### ISSUE TITLE
Cast:get_target_point 返回值问题

### ISSUE THREAD

**Issue by ChouUn** [y3-editor/y3-lualib#535]
演示代码：
```lua
function M.on_cast_shot(ablt, cast)
    local u = ablt:get_owner()

    local p = cast:get_target_point()
    local q = u:get_owner():get_mouse_pos()

    Particle.create({
        type = 100596,
        target = p,
        time = 2,
    })
    Particle.create({
        type = 100104,
        target = q,
        time = 2,
    })

    print('p', p.x, p.y)
    print('q', q.x, q.y)

    local pd = p:get_distance_with(u:get_point())
    local qd = q:get_distance_with(u:get_point())
    print(pd, qd, qd / pd)
end
```
如图所示，
![image](https://github.com/user-attachments/assets/0a2f50c8-1d3c-440d-ade5-85312d0a0607)
目前我的施法点 `p`，会错误定位在蓝色指示物处。
鼠标所在世界位置 `q` ，暨黄色指示物处。
这两者不一致。

`p` 相对于 `u` 的方向是对的，但是距离 `pd` 为实际距离 `qd` 的 1/10，且上限 100. 码）。
本地引擎和编辑器已更新为最新，问下有他人能复现吗？

**Comment by sumneko** [comment]
更新Y3库再试一下

**Comment by ChouUn** [comment]
> 更新Y3库再试一下

仍然如此，我更新 Y3 库一向比较勤快。
![image](https://github.com/user-attachments/assets/ed1f5ad0-6d36-4494-954e-d5d2665fd025)

比较好奇是不是我一个人的问题（

**Comment by sumneko** [comment]
我这边无法复现

**Comment by ChouUn** [comment]
> 我这边无法复现

破案了，是扇形指示器（方向）专属的问题，用原型指示器（地点）就能正确获取到。

请问扇形指示器不能获取到施法目标点，算期望行为吗（

**Comment by sumneko** [comment]
确认了一下设计如此，方向型的技能就是没有施法目标点（只能获取施法方向）。

**Comment by ChouUn** [comment]
> 确认了一下设计如此，方向型的技能就是没有施法目标点（只能获取施法方向）。

行吧，主要是目前仍有点类型的返回值，会令人困惑。
如果故意设计成这样，可能返回 nil 更好理解。

因为不需要解决，暂时关闭问题。
