### ISSUE TITLE
Demo《防守图》启动错误，求解

### ISSUE THREAD

**Issue by wengjincong** [y3-editor/y3-lualib#546]
如题，在main.lua文件中引入'y3.演示.demo.防守图'，提示“error during Python call: ea_prefab_not_exist”。
![1](https://github.com/user-attachments/assets/009edbc0-6386-41f1-9f53-8d2d56b3982c)
![2](https://github.com/user-attachments/assets/bce331b0-98a9-468d-8983-da93792daf93)

**Comment by wengjincong** [comment]
是不是我适用的方式不对，还是啥原因。因为不习惯Y3编辑器的开发思维，看了一下论坛有lua版本的。就果断入了lua版的开发版本

**Comment by sumneko** [comment]
演示图依赖一些物编数据，请阅读一下 readme
