### ISSUE TITLE
还有一个就是game.lua文件649行---获取运动器绑定投射物

### ISSUE THREAD

**Issue by sumneko** [y3-editor/y3-lualib#55]
还有一个就是game.lua文件649行---获取运动器绑定投射物 
function M.get_mover_bound_projectiles() 这个方法似乎没有吧data写到参数里面 
原文:
---@return Projectile projectile 投射物 
---获取运动器绑定投射物 
function M.get_mover_bound_projectiles()
    local py_projectile = GameAPI.get_projectile_by_id(data['mover_owner_projectile'])
    return projectile.get_by_handle(py_projectile)
end

_Originally posted by @200774491 in https://github.com/y3-editor/y3-lualib/issues/45#issuecomment-1656455322_

**Comment by sumneko** [comment]
@200774491

**Comment by 200774491** [comment]
是的可以直接访问,这个可以删了= =。
