### ISSUE TITLE
Projectile 的 get_point() 与 get_height() 表现不一致

### ISSUE THREAD

**Issue by ChouUn** [y3-editor/y3-lualib#553]
调用 Projectile 的
`get_point()` 会错误获得 `(x, y, 0)`，
`get_height()` 能正确获得 `z`。
请问这是期望行为吗（

Unit 的上述接口，是无该问题的。

编辑器: 2.1.2.706839
Y3-LuaLib: 91942d1

**Comment by sumneko** [comment]
现在是这样的，不过可以考虑在Lua的封装里面把z轴补上
