### ISSUE TITLE
使用y3-helper 生成物编的时候会存在 名称和描述乱，就是会改了别的物编的名称，描述会多个物品公用一个，然后一改全变了

### ISSUE THREAD

**Issue by chentangchun** [y3-editor/y3-lualib#561]
如果你想反馈的是编辑器或引擎本身的bug，请反馈至 [论坛](https://create-bbs.reckfeng.com/forum.php?mod=forumdisplay&fid=18) 或者加QQ群：656413818
`export async function 生成装备() {
    const uri = y3.uri(y3.env.pluginUri, '生成装备.xlsx')
    let sheet = await y3.excel.loadFile(uri)

    let table = sheet.makeTable("A1")
    for (let key in table) {

        let data = table[key]

        let unitTable = y3.table.openTable('物品')
        let unitid = Number(data['物品ID'])
        let copyId = Number(data['复制id'])
        let unit = await unitTable.get(unitid)
        if (!unit) {
            if (copyId) {
                unit = await unitTable.create({
                    copyFrom: copyId,
                    key: unitid,
                    overwrite: true,
                })
            }
            else {
                unit = await unitTable.create({
                    key: unitid,
                    overwrite: true,
                })
            }
        }

        unit.data.name = data['装备名']
        let desc = data['技能']
        if (desc == '无') {
            desc = ''
            if (data['属性1']) {
                desc = data['属性1'] + "+" + data['属性加成1']
            }
            if (data['属性2']) {
                desc += data['属性2'] + "+" + data['属性加成2']
            }
            if (data['属性3']) {
                desc += data['属性3'] + "+" + data['属性加成3']
            }
        }
        unit.data.description = desc

    }

    y3.print('666，装备生成成功！')
}`

**Comment by sumneko** [comment]
《Y3开发助手》1.18.5版本修复
