### ISSUE TITLE
装饰物相关方法添加

### ISSUE THREAD

**Issue by 52charlang** [y3-editor/y3-lualib#562]
想用算法自动生成摆件,调用GameAPI.create_deco时只有角度和z轴高度可以调整,而且生成的装饰物没有预设的碰撞(单位可直接穿过),即使该装饰物已经在物编设置过碰撞(用编辑器放置没有问题),所以希望可以改进一下.谢谢

**Comment by sumneko** [comment]
出于性能考虑不支持运行时动态创建装饰物，你可以改成可破坏物

**Comment by 52charlang** [comment]
谢谢,可用
