### ISSUE TITLE
kv_load 加载类型出错

### ISSUE THREAD

**Issue by xiaoyaod** [y3-editor/y3-lualib#565]
local num_attack = unit:kv_load('Num_attack','integer')
    -- Attack1 Ability
    print('num_attack ',num_attack,' ',unit:kv_has(string.format('Attack%d',num_attack)))
    local ability = unit:kv_load(string.format('Attack%d',num_attack),'Ability')
    if ability then
        unit:cast(ability,data.pointing_world_pos)    
    end

![捕获1](https://github.com/user-attachments/assets/26bf3144-f483-4135-aac9-c0b89d86f117)
![捕获2](https://github.com/user-attachments/assets/c62d9b0a-6062-4ff3-9b4d-87778d69d4ce)

**Comment by sumneko** [comment]
'Ability' 指的是技能对象。技能类型我加一下

**Comment by sumneko** [comment]
直接用 `integer` 类型即可

**Comment by xiaoyaod** [comment]
编辑器 拷贝ID  有点困难  需要改进下

**Comment by sumneko** [comment]
> 编辑器 拷贝ID 有点困难 需要改进下

具体哪里？

**Comment by xiaoyaod** [comment]
![微信图片编辑_20241224154046](https://github.com/user-attachments/assets/bfa59165-7d60-4ce9-be40-21ebeac8dfe4)


{2048: 
 [{'type': 2048, 'name': 'Level1', 'height': 28.039331436157227, 'width': 22.199512481689453, 
   'color': None, 'weather': 7, 'sound': None, 'scale': (4.439902305603027, 1.0, 5.607866287231445), 
   'tags': OrderedSet(), 'offset': [0.0, 0, 0.0], 'group_key': 2048}], 
   'is_clicli_select_copy': 175897143754968813980231418450497145602}

ctrl + c 出来的数据没有id 
y3.rect.get_res_id()数据 的数据没有拿到


帮忙看下这个  https://github.com/y3-editor/y3-lualib/issues/563
