### ISSUE TITLE
看不到报错了

### ISSUE THREAD

**Issue by summmmmmmmn** [y3-editor/y3-lualib#570]
local unit = y3.player:create_unit()

然后 aaaa是不存在的，但是
unit.aaaa:event_on()是不会报错的。。

unit.a = 'a'
unit.b = 1
unit.a + unit.b这样也不会不报错了

y3对象现在不支持这样加自定义字段了吗

**Comment by sumneko** [comment]
贴一下代码和报错信息

**Comment by summmmmmmmn** [comment]
哦没事了，前几天的lib还不行，刚更新了一下能看到了
