### ISSUE TITLE
玩家加入事件中的二参数data和script/y3 中返回的数据结构不一致

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#6]
1. 之前 data.player 可以获取到 lua player。现在 data 本身就是 lua player 对象
2. 现在事件传递的 lua player 对象，缺少get_id 等方法

![_20230703160829](https://github.com/y3-editor/y3-lualib/assets/12406222/91ff2d5e-1df5-46a6-b417-2b0e4321e0f1)
![_20230703160856](https://github.com/y3-editor/y3-lualib/assets/12406222/51174fe2-789a-406f-9718-2c9063178eca)
![_20230703160912](https://github.com/y3-editor/y3-lualib/assets/12406222/078764df-3797-4f12-94d6-685aa16d9e53)

**Comment by sumneko** [comment]
试试

**Comment by xiazhixi** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/12406222/c9311878-9c7e-49de-8206-730207fb1a03)
这样不行
![_20230703212333](https://github.com/y3-editor/y3-lualib/assets/12406222/843737aa-5c4e-42b3-ac96-00f63b47e5db)
这样也不行

![image](https://github.com/y3-editor/y3-lualib/assets/12406222/51de999c-2d8f-41f5-96b3-65d6cf21de8a)


虽然我可以通过 player.id 获取到玩家 id。但是我理解的是 runtime_object 的 Player 的实例对象上应该都有那些个方法

**Comment by sumneko** [comment]
`data.player` 就是玩家对象，可以直接调用 `data.player:get_id()`

**Comment by xiazhixi** [comment]
data.player:get_id() 报错
![_20230703213535](https://github.com/y3-editor/y3-lualib/assets/12406222/aaede7c2-3471-402f-84a5-b5604836ff43)

> `data.player` 就是玩家对象，可以直接调用 `data.player:get_id()`

**Comment by xiazhixi** [comment]
> `data.player` 就是玩家对象，可以直接调用 `data.player:get_id()`

可以了，刚刚手滑写错了，感谢解答 ~ 辛苦啦
