### ISSUE TITLE
Debug断点问题

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#61]
问题：
用lua进行debug的时候能随时加断点吗，我这边试了很多次都是只有进入程序的时候wait的指令哪里触发一下，而且触发之后的文件是<memory>的并不是本地的lua文件，运行中加的断点也是不生效的...

这个是能DEBUG的吗?

**Comment by sumneko** [comment]
readme里有调试方法

**Comment by xiaoqiangCai** [comment]
> readme里有调试方法

所以我想确认一下，正常的是应该可以随时加断点的吧

**Comment by sumneko** [comment]
如果你确定你的调试方法与readme里的一致，请尝试以下流程：
1. 检查你的编辑器是最新的
2. 在 `wait` 处中断成功后，按下 `Ctrl+Shift+Y` 打开调试控制台
3. 在控制台中输入 `debug.getinfo(3)` ，回车提交
4. 调试控制台中应该会显示一个结果，鼠标点一下把它展开，然后截图发在这里（注意截完整）

**Comment by xiaoqiangCai** [comment]
> 3\. debug.getinfo(3)

更新vscode花了点时间，截图如下

![image](https://github.com/y3-editor/y3-lualib/assets/7403230/9463a7a2-a6ae-4d97-84fd-fa72d6732f21)

**Comment by sumneko** [comment]
> > 3. debug.getinfo(3)
> 
> 更新vscode花了点时间，截图如下
> 
> ![image](https://user-images.githubusercontent.com/7403230/257747086-9463a7a2-a6ae-4d97-84fd-fa72d6732f21.png)

你的Y3编辑器是最新的吗？

**Comment by xiaoqiangCai** [comment]
> > > 3. debug.getinfo(3)
> > 
> > 
> > 更新vscode花了点时间，截图如下
> > ![image](https://user-images.githubusercontent.com/7403230/257747086-9463a7a2-a6ae-4d97-84fd-fa72d6732f21.png)
> 
> 你的Y3编辑器是最新的吗？

我的截图不正常吗，正常的应该是啥样的

**Comment by xiaoqiangCai** [comment]
> > > > 3. debug.getinfo(3)
> > > 
> > > 
> > > 更新vscode花了点时间，截图如下 ![image](https://user-images.githubusercontent.com/7403230/257747086-9463a7a2-a6ae-4d97-84fd-fa72d6732f21.png)
> > 
> > 
> > 你的Y3编辑器是最新的吗？
> 
> 我想起一件事：Y3群里的debug方法跟github的多了一步这个 ![image](https://user-images.githubusercontent.com/7403230/257757218-bbffb5b4-0305-4dcc-8049-2170dff54f1e.png)

没啥用，我移除这个，现象是一样的

**Comment by ldoubil** [comment]
可以随时断点,但是不能在main文件里要require 一个

**Comment by sumneko** [comment]
> 可以随时断点,但是不能在main文件里要require 一个

这个要等下个版本修复

**Comment by xiaoqiangCai** [comment]
> > 可以随时断点,但是不能在main文件里要require 一个
> 
> 这个要等下个版本修复

是今天更新的版本吗，我试了一下还是不行，表现跟之前一样
![image](https://github.com/y3-editor/y3-lualib/assets/7403230/0ceca806-b731-4bc3-a663-38dac2de8c3d)

**Comment by sumneko** [comment]
我问一下会在哪个版本更新

**Comment by xiaoqiangCai** [comment]
> 我问一下会在哪个版本更新

hi，还是不太行，有啥临时的解决办法吗，给我感觉似乎你们都能，就少部分人不行的样子...

**Comment by sumneko** [comment]
> > 我问一下会在哪个版本更新
> 
> hi，还是不太行，有啥临时的解决办法吗，给我感觉似乎你们都能，就少部分人不行的样子...

先 `main.lua` 里直接 `require` 另一个文件吧

**Comment by xiaoqiangCai** [comment]
> > > 我问一下会在哪个版本更新
> > 
> > 
> > hi，还是不太行，有啥临时的解决办法吗，给我感觉似乎你们都能，就少部分人不行的样子...
> 
> 先 `main.lua` 里直接 `require` 另一个文件吧

一直都是require其他文件的，无法触发新断点，现在的状态是断点功能等同于没有

**Comment by sumneko** [comment]
> > > > 我问一下会在哪个版本更新
> > > 
> > > 
> > > hi，还是不太行，有啥临时的解决办法吗，给我感觉似乎你们都能，就少部分人不行的样子...
> > 
> > 
> > 先 `main.lua` 里直接 `require` 另一个文件吧
> 
> 一直都是require其他文件的，无法触发新断点，现在的状态是断点功能等同于没有

等下个版本更新看看吧，我这边测试是正常的，也许你上次版本更新有问题？

**Comment by xiaoqiangCai** [comment]
> > > > > 我问一下会在哪个版本更新
> > > > 
> > > > 
> > > > hi，还是不太行，有啥临时的解决办法吗，给我感觉似乎你们都能，就少部分人不行的样子...
> > > 
> > > 
> > > 先 `main.lua` 里直接 `require` 另一个文件吧
> > 
> > 
> > 一直都是require其他文件的，无法触发新断点，现在的状态是断点功能等同于没有
> 
> 等下个版本更新看看吧，我这边测试是正常的，也许你上次版本更新有问题？

不知道啊，上次我跟你说了之后还重装了kk，软件上的版本应该是没问题的，要不就是系统设置啥的了，VPN/hosts什么的，会有影响吗

**Comment by sumneko** [comment]
确认是独立客户端模式才有的问题，引擎这边今天修了

**Comment by xiaoqiangCai** [comment]
> 确认是独立客户端模式才有的问题，引擎这边今天修了

好的，试了，确实内嵌打开的debug功能好使，独立的今天试了还是不行的，等修复了
