### ISSUE TITLE
[引擎BUG] 1.2.35 版本引擎恶性bug!---已修复

### ISSUE THREAD

**Issue by ldoubil** [y3-editor/y3-lualib#68]
### 复现bug办法
![image](https://github.com/y3-editor/y3-lualib/assets/26994456/d3fcdbbb-b20c-4645-bc9d-6a75d9d2713f)
[https://i.postimg.cc/rwgMDx4P/1690995463937-2.gif](url)
gif 预览
[1690995463937-2.gif](https://postimg.cc/zyL9ML0C)

**Comment by 200774491** [comment]
群内找管理反馈

**Comment by ldoubil** [comment]
> > ### 1.2.35 更新后的引擎,第三人称相机彻底无法使用,会抽搐无法控制.
> > ### 目前项目已经无法继续开发,希望能帮忙反馈到引擎修复.
> > ### 新建项目测试一样出现bug.
> > ### 复现bug办法
> > ![图像](https://user-images.githubusercontent.com/26994456/257886140-d3fcdbbb-b20c-4645-bc9d-6a75d9d2713f.png) [https://i.postimg.cc/rwgMDx4P/1690995463937-2.gif](url) gif 预览 [1690995463937-2.gif](https://postimg.cc/zyL9ML0C)
> 
> ![图像](https://user-images.githubusercontent.com/94234842/261487874-09783fd4-909f-44c4-a453-191556c73bbb.png)可以这样

次issues为bug所导致1.2.35版本后续已经修复与写法无关

**Comment by ldoubil** [comment]
> ### 1.2.35 更新后的引擎,第三人称相机彻底无法使用,会抽搐无法控制.
> ### 目前项目已经无法继续开发,希望能帮忙反馈到引擎修复.
> ### 新建项目测试一样出现bug.
> ### 复现bug办法
> ![image](https://user-images.githubusercontent.com/26994456/257886140-d3fcdbbb-b20c-4645-bc9d-6a75d9d2713f.png) [https://i.postimg.cc/rwgMDx4P/1690995463937-2.gif](url) gif 预览 [1690995463937-2.gif](https://postimg.cc/zyL9ML0C)

已修复
