### ISSUE TITLE
[需求]鼠标跟随建议加XY偏移参数

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#70]
-- 设置控件跟随鼠标
---@param follow_mouse boolean
function M:set_follow_mouse(follow_mouse)
    GameAPI.set_ui_comp_follow_mouse(self.player.handle, self.handle, follow_mouse)
end

建议:
-- 设置控件跟随鼠标
---@param follow_mouse boolean
function M:set_follow_mouse(follow_mouse,x,y)
    GameAPI.set_ui_comp_follow_mouse(self.player.handle, self.handle, follow_mouse,x,y)
end

**Comment by 200774491** [comment]
否则这个func很鸡肋

**Comment by sumneko** [comment]
你设置一个空白控件跟随鼠标，然后再创建空白控件的子控件就行了

**Comment by 200774491** [comment]
机智
