### ISSUE TITLE
帧回调事件不生效

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#72]
帧回调事件都是假的吗，注册成功了，不会触发回调

---@field event fun(self: self, event: "时间-经过帧", count: integer, callback: fun(trg: Trigger, data: EventParam.时间-经过帧)): Trigger

---@field event fun(self: self, event: "时间-周期帧", count: integer, callback: fun(trg: Trigger, data: EventParam.时间-周期帧)): Trigger

**Comment by sumneko** [comment]
已经修复了
