### ISSUE TITLE
LUA调用ECA

### ISSUE THREAD

**Issue by xiaoqiangCai** [y3-editor/y3-lualib#73]
好多y3库里面提供的gameapi的接口都是假的，但是eca是可以的，再没有修复api的情况下，有办法能lua调用eca的函数吗

比如：
--播放UI控件时间轴动画
function GameAPI.play_ui_comp_anim() end

**Comment by sumneko** [comment]
GameAPI就是你要的方法，有无效的就汇报修复

**Comment by xiaoqiangCai** [comment]
> GameAPI就是你要的方法，有无效的就汇报修复

好吧，业务不等人，lua调用eca目前是不通的，是吗

**Comment by sumneko** [comment]
你可以认为ECA是另一种编程语言，他也是通过API来调用引擎的功能的。

**Comment by sumneko** [comment]
你用 `UI:play_timeline_animation` 试试？

**Comment by xiaoqiangCai** [comment]
> play_timeline_animation

已经自己写运动函数做UI的动画了....
