### ISSUE TITLE
存档api, Role:get_save_table_key_value 的参数 value_convert_func 如何使用?

### ISSUE THREAD

**Issue by xuhuanzy** [y3-editor/y3-lualib#78]
get_save_table_key_value 无法取出 table 类型的值. 
存档结构为: 
```lua
{
        x = {
            y = {
                z = 1,
                z2 = 2,
            }
        }
```
y3.player(1).handle:get_save_table_key_value(1, "x", 'y', '', '', '') 返回值为空

**Comment by sumneko** [comment]
研究了一会儿不知道这个存档怎么玩，直接转交给相关的同学处理了

**Comment by sumneko** [comment]
最后的3个参数改成 `nil` 试试？

**Comment by xuhuanzy** [comment]
> 最后的3个参数改成 `nil` 试试？
后面三个参数前两个是key 最后一个是 value_convert_func , 不给 value_convert_func  设置值就不会报错.

**Comment by sumneko** [comment]
可以正常工作吗？

**Comment by sumneko** [comment]
晚点封装一下
