### ISSUE TITLE
我印象里我看到过一个生成api的工具吧?

### ISSUE THREAD

**Issue by CabinIkaros** [y3-editor/y3-lualib#80]
怎么现在没了,编辑器里是否有什么命令或工具可以导出最新的api?我想做一些其他语言的处理,比如ts

**Comment by sumneko** [comment]
直接用Lua插件 `右键 -> 导出文档` 即可

**Comment by CabinIkaros** [comment]
> 直接用Lua插件 `右键 -> 导出文档` 即可

插件名叫啥

**Comment by sumneko** [comment]
https://marketplace.visualstudio.com/items?itemName=sumneko.lua

**Comment by CabinIkaros** [comment]
> https://marketplace.visualstudio.com/items?itemName=sumneko.lua

好的,感谢
