### ISSUE TITLE
[BUG反馈] 设置单位名称后血条名称显示依然是单位类型的名称

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#84]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/07ed32af-417d-47da-a1b9-7eaf913cf4f7)

**Comment by 200774491** [comment]
修复之后提示对了但是名称依然是错误的
如下:
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/d9150f00-a19a-4bd5-8402-394dc57cc4f9)
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/257083d3-c98c-45fb-9d9b-6983d05fa6bb)
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/aef02502-839e-4af9-a1b6-629bfd795e28)
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/5ad26959-cf40-46ac-802b-d1847da99628)

**Comment by sumneko** [comment]
还没修复呢...

**Comment by 200774491** [comment]
- -修复了之前提示是物品模版,今天提示有有设置后的名称了

**Comment by 200774491** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/dfc9ea92-9360-4e7a-b33e-853a3f4f0ee9)
额确定修复了但是没修复对 ..

**Comment by 200774491** [comment]
set_name 后设置之后的名字在改变就不行了.....
感觉好不细心建议叼一下

**Comment by 200774491** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/3ffdfe15-69f0-4ffc-a402-dab7a9ac44ef)
哈哈哈,我草
建议先叼一遍
