### ISSUE TITLE
[bug反馈] 开启透视移动单位后会失效

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#85]
---设置透视状态
---@param is_open boolean 是否透视
function M:set_Xray_is_open(is_open)
    self.handle:api_set_Xray_is_open(is_open)
end

这个是否和
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/d5165364-fe97-4557-876e-baf0e18b298b)
这个有关？
然后就是如果在编辑器内设置开启透视
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/b4ebf1c7-d98b-44ca-b3c3-0c56d5ab3af4)
移动单位后会失效

**Comment by HongkaiD** [comment]
具体效果是什么样的？编辑器勾选开启透视，然后单位在被遮挡的时候移动，效果会消失？

**Comment by 200774491** [comment]
是的 单位被遮挡时候移动效果会消失我给你录屏看吧

**Comment by 200774491** [comment]
你可以试试丢一个装饰物然后再丢给一个单位 单位要被装饰物遮盖,然后测试游戏进入游戏后移动单位 效果消失

**Comment by 200774491** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/2c1694fd-414b-4c59-99db-674c76ecaf06)
zuo左移动后, 右边未移动

**Comment by HongkaiD** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/75577452/2dcb60e6-3d1b-4d7b-9084-4747d4cb19d8)
![image](https://github.com/y3-editor/y3-lualib/assets/75577452/a1ebf677-2d1f-42ef-a8b4-04a5adb4db4e)
我这里没有复现成功，可以把你的地图文件发一下吗？

**Comment by 200774491** [comment]
你加我Q 200774491

**Comment by sumneko** [comment]
已经沟通过这和另一个功能有冲突导致的，不算是bug。
