### ISSUE TITLE
[bug反馈] 物品对象问题

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#87]
物品对象绑定特定数据似乎会消失
我不确定,但是我这边测试确实是这样
例如: A()方法内 创建的item 并给物品绑定数据 item.a = "s" 传递item 出去 后 在B()内 print(item.a)得到的结果应该是"s"但是我得到了nil

**Comment by 200774491** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/03d26ba4-eb02-4f54-a81c-0deff0da4205)
我具体没看
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/4ed45201-d999-46f7-8220-a5e7839ce0a3)
是怎么获取的
从我得到结果来看应该是又重新定义了一个对象

**Comment by 200774491** [comment]
完整代码
-- 初始化之后,创建物品
local it = y3.item.create_item(y3.unit.get_by_id(11):get_point(),134261191,y3.player(1))
it.a = "s"
y3.game:event("物品-获得",function(_,data)
    local item_id = data["_py_params"]["__item_id"]
    local test_itme = y3.item.get_by_id(item_id)
    -- local test_itme = y3.item(item_id)
    print(test_itme:get_name())
    print("得到的数据",test_itme.a)
end)

**Comment by 200774491** [comment]
单位对象就不会发生这种情况

**Comment by 200774491** [comment]
![image](https://github.com/y3-editor/y3-lualib/assets/138980212/473200c8-dfc8-4cfb-904b-6d17d3d423b6)
单位对象就不会发生这种情况,因为我都是转发的

**Comment by sumneko** [comment]
使用的最新版本吗？

**Comment by 200774491** [comment]
我不确定,我拉一个最新的在试试

**Comment by 200774491** [comment]
最新版本的解决了这个问题

**Comment by sumneko** [comment]
建议用 `storage_set` 和 `storage_get` 方法，只有我保证对象唯一性的类型才会有这2个方法，而且可以避免与未来的API冲突。
