### ISSUE TITLE
[优化补充] item_attr相关

### ISSUE THREAD

**Issue by 200774491** [y3-editor/y3-lualib#89]
---设置基础属性
---@param key string 属性key
---@param value number 属性值
function M:set_attribute(key, value)
    self.handle:api_set_attr("ATTR_BASE", key, value)
end

---增加基础属性
---@param key string 属性key
---@param value number 属性值
function M:add_attribute(key, value)
    self.handle:api_change_attr("ATTR_BASE", key, value)
end

---获取物品的基础属性
---@param key string 属性key
---@return number
function M:get_attribute(key)
    return self.handle:api_get_attr("ATTR_BASE", key)
end

这些的返还值没处理 少加一个:float()
其他的我没测试

**Comment by 200774491** [comment]
---增加基础属性
---@param key string 属性key
---@param value number 属性值
function M:add_attribute(key, value)
self.handle:api_change_attr("ATTR_BASE", key, value)
end

这个是复制错的

**Comment by 200774491** [comment]
---增加基础属性
---@param key string 属性key
---@param value number 属性值
function M:add_attribute(key, value)
self.handle:api_change_attr("ATTR_BASE", key, value)
end
这个不是

**Comment by sumneko** [comment]
设置应该也不是吧？

**Comment by 200774491** [comment]
设置不是。。我复制的

**Comment by 200774491** [comment]
获取的有几个数据没转换
