### ISSUE TITLE
多开运行会因为debugger卡死在0%

### ISSUE THREAD

**Issue by xiazhixi** [y3-editor/y3-lualib#9]
![_20230704115835](https://github.com/y3-editor/y3-lualib/assets/12406222/bc0829bb-a031-4bd7-8c95-64901a5d9a44)

**Comment by xiazhixi** [comment]
注释掉 debugger 以后，加载不会被阻塞，但也会有报错
![image](https://github.com/y3-editor/y3-lualib/assets/12406222/69446263-ddc1-4e2e-87d7-458ce5a3ce75)
![image](https://github.com/y3-editor/y3-lualib/assets/12406222/998c8f24-5bd3-4202-8fe9-34eb06e5391d)

**Comment by sumneko** [comment]
你是启用了 `LDBG:event 'wait'` 嘛？

**Comment by xiazhixi** [comment]
> 你是启用了 `LDBG:event 'wait'` 嘛？

没有，新起了项目，直接是用的
```lua
pcall(function ()
    LDBG = require "y3.debugger":start "127.0.0.1:12399"
end)
```
就是直接拉了 main 放在 y3 目录

vsc 没有启动 F5，本地多开只勾选一个玩家。必现

**Comment by sumneko** [comment]
我这边测试没法再现，可能是版本问题，等下个客户端版本再试试吧，目前先把调试器注掉吧

**Comment by sumneko** [comment]
似乎编辑器内运行和本地多开运行的环境不一样，我之后再研究这个问题
