### ISSUE TITLE
Lua中创建的UI看不到,但是打印有ui而且不管传什么类型得到的ui都是button

### ISSUE THREAD

**Issue by CabinIkaros** [y3-editor/y3-lualib#90]
这是测试代码

```
        local player = y3.player:alloc(1)
        print(player:get_name())
        local point = y3.point:alloc(0, 0, 0)
        print(point)
        local hero = player:create_unit(134274912, point, 0)

        local hud = y3.ui.get_ui(player, "GameHUD")
        local ui = y3.ui.create_ui(player, hud, 5)
        ui:set_pos(100, 100)
        ui:set_anchor(100, 100)
        ui:set_ui_size(150, 50)
        ui:set_visible(true)
        ui:set_text_color(255, 255, 255, 255)
        ui:set_font_size(18)
        ui:set_text(hero:get_name())
        print(ui)
```
![image](https://github.com/y3-editor/y3-lualib/assets/81321122/9b8bdb85-0176-492f-860f-32a0ad730ee7)

![image](https://github.com/y3-editor/y3-lualib/assets/81321122/246dac04-c913-46b3-8f27-75f72e78c716)

**Comment by 200774491** [comment]
local main = y3.ui.get_ui(y3.player(1), 'panel_1')
    local image = main:create_child('图片')
    image:set_pos(100, main:get_height() / 2)
    image:set_image(106330)
    你试试其他创建方式

**Comment by sumneko** [comment]
`local ui = y3.ui.create_ui(player, hud, 5)` 第3个参数请按照插件提示传枚举值

**Comment by CabinIkaros** [comment]
> `local ui = y3.ui.create_ui(player, hud, 5)` 第3个参数请按照插件提示传枚举值

感谢,看到了,lua里会自己去拿枚举值=-=
