### ISSUE TITLE
框架进展问题

### ISSUE THREAD

**Issue by padoruuu** [y3-editor/y3-lualib#91]
由于近期需要做技能和物品了，还是没忍住想问一下，大概什么时候会支持英萌那种写法呢，比如本月内?
魔兽转y3的lua作者都是用的英萌这一套框架，主要习惯了这种写法0.0
如果可以的话，伤害流程，属性系统也都想使用英萌那套QWQ

local mt=ac.skill['技能A']
mt{
level=1,
}
function mt:on_cast_start()
    local hero = self.owner
    local skill = self
    
end

**Comment by 200774491** [comment]
你自己写啊,小夕提供的是库你转发封装一下就行了啊

**Comment by sumneko** [comment]
下周

**Comment by sumneko** [comment]
事件已经可以注册了，见更新说明。

定义物编数据还需要开发
